### ISSUE TITLE
PNG export wizard

### ISSUE THREAD

**Issue by Kroc** [tannerhelland/PhotoDemon#118]
I just can't do what I need with PD, there's enough control over PNG saving for web work!

There's no implicit way to convert the current image from 32-bit to 8-bit indexed with 1-bit transparency. Despite various attempts, it's always giving me a 32-bit file.

I load the image, use "Remove Transparency" to composite the background colour I want, then "Make Color Transparent" to clip the background out, leaving the composited shadows.

But it still saves as a 32-bit PNG!

Please provide one or both of the following:

* A menu item to reduce / increase the image bit-depth, including choosing background and transparent colours

* A PNG window when saving to handle this at save-time

**Comment by Kroc** [comment]
"I would have gotten away with it, if it wasn't for your meddling, VB6!"

If the theme handler for each control subclassed the form and listened out for a custom window message, you could get them to all repaint without having to iterate them.

**Comment by tannerhelland** [comment]
Indeed, I have used that workaround elsewhere to reasonable effect.  (I say "reasonable" because it's still a bit ugly, to be honest - VB windows are inclined to eating window messages they don't understand, so PD actually stores a list of windows that register for a given custom message, and manually blasts those specific windows as necessary.  It's ugly, but possibly a good workaround here.)
