### ISSUE TITLE
Context menu on image tabs

### ISSUE THREAD

**Issue by Kroc** [tannerhelland/PhotoDemon#119]
Would be nice to be able to right-click the image thumbails and get an option to close the image and perhaps anything else relevant.

**Comment by rajch** [comment]
What, other than close, would be relevant on thumbnails? Save/Save As is the only thing I can think of. We could do that by making the existing "unsaved" icon clickable. A context menu with only one or two items looks a bit odd.

**Comment by tannerhelland** [comment]
@rajch, that's a great question.  Some of the items I'd originally considered adding (like "Save a lossless copy") have since been integrated into the left-side toolbar, and other potential options (like "Save for Web") don't exist yet.

One item I'd considered before was "open this file's location in Explorer", but aside from that, I don't have any immediate ideas for a context menu.  We can probably postpone such a menu for now, at least until we have a better idea of what it might include.

**Comment by Kroc** [comment]
Since the tab represents the "window" for that document, the context menu should include window commands from the window menu, but on top of this I can think of _"Close other tabs"_

**Comment by tannerhelland** [comment]
"Close other images" is a good suggestion.  There's not much of interest in PD's Window menu right now.  In the future, support for things like multiple viewports (e.g. side-by-side edit windows) could make a context menu more interesting, but at present, we'd need to newly implement most interesting items in a context menu.

At a glance, browsers provide some potentially interesting analogs:

- Move image to new window
- Reload ("Revert" analog in PD)
- Close this tab (image)
- Close all other tabs (images)
- Close tabs (images) to the right
- Undo last closed tab (image)
- Duplicate this tab (image)

Code exists in PD for some of these, but not all.  I'm leery to implement major new features so close to 6.6's release, so Raj, if you want to push your existing work as-is, I think that would be great!  Maybe we could revisit this in a few weeks as potential features for 6.8?
