### ISSUE TITLE
build 652 - Modern Art: no effect

### ISSUE THREAD

**Issue by fvbeers** [tannerhelland/PhotoDemon#154]
RW2 (Panasonic RAW), opened , effect after applying not visible 
http://inft.ly/t7BV5W8
http://inft.ly/WRd5y9Q

**Comment by tannerhelland** [comment]
The effect is there, you just have to zoom in to see it!  :)  On such large images, the main screen is limited to less than 25% zoom (depending on your monitor's resolution), so 1-pixel effects may be difficult to see without zooming in to 100%.

Some effects, like Modern Art, cannot physically resolve to less than 1px, so they may appear slightly different in the preview window (which is operating on a tiny copy of the image), versus the main screen.  I'm afraid I don't know a way around this, but in the future when previews are finally moved to the main window, this kind of thing will be less likely to occur...

**Comment by fvbeers** [comment]
Thanks for explaining Tanner!

**Comment by tannerhelland** [comment]
Okay, what I've done is modified the tool a bit, so that the preview will appear to have no effect at all if the radius is too small for the current image.  That way, the user should know to either check 100% zoom on the preview box, or increase the strength until the effect becomes more visible.  (This is as close to a "fix" as I can think of, using the current system.)

Thanks again for reporting!
