### ISSUE TITLE
Opening RW2 (Panasonic RAW)

### ISSUE THREAD

**Issue by fvbeers** [tannerhelland/PhotoDemon#155]
strange distortions in corners, happens in some other editors too!
Original RAW and PD-jpg: http://inft.ly/SzwK9S8
greetings from Eindhoven,
Frans

**Comment by audioglider** [comment]
I tested your original RAW file in PD and Lightroom also, it appears to be lens vignetting caused by the original camera. It's caused by the lens actually capturing its own sides. I was able to correct it using the lens distort correction tool. Try a correction strength of 1.44 and zoom at 1.00.

**Comment by fvbeers** [comment]
thanks for testing and explaining! When I shoot JPG with my Panasonic DMC-FZ1000 it's not here, so the camera corrects itself?  When I open/edit the RW2 in my standard Zoner Photo Studio Pro the vignetting is not present..

**Comment by tannerhelland** [comment]
Hi Frans.  PhotoDemon uses the open-source LibRaw library (http://www.libraw.org/) for processing RAW files.  This is the best library I know of for processing RAW files, and a ton of other software uses it too (PhotoShop among them).

The trouble with RAW files is that many manufacturers do not document their RAW formats, so the only way for other software to load those files, is to try and reverse-engineer the format themselves.  Sometimes this results in images that are slightly different from what the camera itself produces in JPEG mode, because the library does not have access to the proprietary code used by the manufacturer.

Given enough time, LibRaw usually works through these issues, and when they do, you will suddenly notice that a ton of different software can "magically" load the RAW files in question.  If you are interested, you might try submitting your RAW file directly to the LibRaw team.  They can fix this more easily than I could, due to their familiarity with RAW formats in general.  Also their fix would help many different programs, not just PD!

(Alternatively, they may not address vignetting automatically - I'm afraid I'm not very familiar with the inner guts of the library, or how they feel about applying auto-corrections like that.)

**Comment by audioglider** [comment]
Frans, yes. When shooting in JPG mode, the camera often corrects this distortion internally. Also, I don't believe your camera model is supported by libRaw yet since it's newer. It is currently just doing it's best to read the raw data from the file as Tanner explained. Are you experiencing this distortion with other photos as well?

**Comment by tannerhelland** [comment]
As a technical addendum, PD uses LibRaw as included in FreeImage.  PD's custom-patched FreeImage is updated against the latest LibRaw GitHub patch (from November last year, https://github.com/LibRaw/LibRaw).  LibRaw development is unpredictable, so I have no idea when the next update will release, but PD's nightly builds should be among the best when it comes to patching against the latest LibRaw...

(Thanks much @audioglider for your help.)

**Comment by fvbeers** [comment]
thank you both for explaining and the information provided! Yes it happens with other pics too!
I'll contact libraw and send in a example. Good thing the tool in PhotoDemon easily corrects all :-)

**Comment by tannerhelland** [comment]
Frans, do identical lens distort correction values work on every image from that camera?  Or does the distortion vary from image to image?

If they're always identical, I wonder if I could implement some kind of auto-macro system, where the user could specify a macro to apply to images that meet certain criteria (maybe some kind of metadata match).  That way, photos from that camera could be auto-corrected any time they were loaded into the program...  

If they're not identical, it's a nastier problem, but maybe there's still something in the metadata we could use to suggest a correction value.  I'll see what I can turn up.

**Comment by fvbeers** [comment]
Tanner, I used to shoot in JPG only, but this week I'm going to take pictures in a great diary plant in Eindhoven, so I'll have much more RAW files to check it out. I'll get back to you on this issue later!

**Comment by tannerhelland** [comment]
Thank you!  Have a great trip!

**Comment by tannerhelland** [comment]
PD has been updated against FreeImage 3.17, which includes the latest LibRaw alpha released just this month (http://www.libraw.org/).  The latest LibRaw build added support for a bunch of Panasonic cameras, so I'm hoping this issue magically resolved itself.  (If not, Frans, please let me know!)
