### ISSUE TITLE
ComboBox open animation incorrect at bottom of screen.

### ISSUE THREAD

**Issue by Kroc** [tannerhelland/PhotoDemon#171]
Easily seen with the Font ComboBox, the opening animation is played as if opening the menu below (slide-down) rather than above (slide-up).

**Comment by tannerhelland** [comment]
I have searched and searched for a solution to this, but I can't find a thing on how to override or modify the animation programmatically.  If you have any insider tips, I'd welcome them!

**Comment by Kroc** [comment]
Subclass it and use the `AnimateWindow` API manually?

**Comment by tannerhelland** [comment]
Hmm, I thought that API had issues under Aero, but I will give it a try and report back.  Thanks!

**Comment by Kroc** [comment]
I googled around and couldn't find any particular indication. There's no manual painting required, so there's nothing inherently incompatible about it. For Vista and above you can use the [`GetThemeTransitionDuration`](https://msdn.microsoft.com/en-us/library/windows/desktop/bb759804%28v=vs.85%29.aspx) API to know how long to animate the slide for, you can probably gank it from the registry somewhere in XP.

**Comment by tannerhelland** [comment]
I think it was more to do with performance issues, due to the way Aero handles compositing.  The  [MSDN page] (https://msdn.microsoft.com/en-us/library/windows/desktop/ms632669%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) states drop-shadows as a culprit, so possibly that's the determining factor?

I'm not on Windows right now but will try this later tonight.  Some other registry spelunking will be needed, i.e. to see if animations are even enabled by the user.  (Specific animation settings may be ugly to retrieve, per [links like this] (http://stackoverflow.com/questions/23044933/detecting-windows-animation-settings).)

**Comment by Kroc** [comment]
One can turn the shadow off during animation by setting some Windows style bits

**Comment by tannerhelland** [comment]
Now that I'm no longer using API combo boxes, it will be possible to animate the dropdown window however we want.  I'll close this issue for now as this problem technically no longer exists (the current implementation is not animated at all).

Animation for all of PD's controls is on my to-do list and when that day comes, this will be dealt with too!

**Comment by Kroc** [comment]
Indeed. I only ask that, if possible, to pull the system animation settings from the registry.
