### ISSUE TITLE
Bug report: error number 9 - subscript out of range

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#175]
I got an error that said
"Error number 9
Description: Subscript out of range"
I'm using Window XP 32 bit, PhotoDemon 6.6. Below are steps I took to get the error
1) I open an arbitragy image then choose Tools -> Record Macro -> Start recording
2) I choose File -> Import -> Online Image. I copy this link into the field http://img.v3.news.zdn.vn/Uploaded/pgi_xvauqbnau/2013_10_06/stevejobs.jpg then press OK.
3) After the image is loaded, I choose Tools -> Record Macro -> Stop recording and save it as "stevejob.pdm"
4) Now I play the macro: I choose Tools -> Play macro and choose the file stevejob.pdm. I see the line "Loading macro data..." but after 2 minutes, it still says loading (I think there is an other error here when it loads too long) so I try to reopen the macro by choosing Tools -> Play macro and choosing the file stevejob.pdm and the error shows up.
I have tried the above steps two times and the error keep appearing.

**Comment by tannerhelland** [comment]
Hi vhreal1302.  Thank you very much for submitting this bug report.  I have confirmed the bug in the latest developer builds of PhotoDemon, so this problem has been around for many months!

PhotoDemon automatically strips image import/export data from a macro file before writing it to file.  Because the only recorded action in your "stevejob.pdm" macro is an import action, no macro steps are recorded to file.

The "Play macro" function assumes there is at least one valid macro step in the file, which is a faulty assumption!  So it breaks on this typical macro, as it can't find anything to play back.  I clearly need to add a failsafe check for this possibility.

Ideally, I also need to add a message prior to saving a macro with only import/export data.  I have added this to my to-do list.  Thank you again for bringing this bug to my attention.

Quick question - would it be useful to record "Import file from Internet" steps as part of a macro?  I specifically designed macros to *not* work this way, but if that's something you find useful, I can add an option to keep "import image" steps inside the macro file.  Thanks in advance for your feedback.

**Comment by vhreal1302** [comment]
Thank you for your offer but I do not import file from Internet much so I think you do not need to change it.

**Comment by tannerhelland** [comment]
Perfect, thank you.  I have just fixed this bug in the latest development builds.

I am happy to add your name to the contributor list for the next release, as a "thank you" for your very helpful bug report.  If that's okay with you, please let me know what name (and optionally, website) you would like me to use in the program and on the PhotoDemon website.  Thanks!

**Comment by vhreal1302** [comment]
You can use my full name Nguyen Van Hung.
