### ISSUE TITLE
CRASH: Bad value in width/height box

### ISSUE THREAD

**Issue by jpbro** [tannerhelland/PhotoDemon#176]
On the Create New Image and Resize Layer windows - if you type a bad numeric value (e.g. a simple typo like 18-3 instead of 1803) into and then press Tab, PD will crash.

**Comment by tannerhelland** [comment]
Hi jpbro.  Thank you for reporting this.  I believe it's the same problem as Issue #172, "CRASH: Pressing tab on a textbox in the resize dialog".

Did you experience the crash on the last stable release?  (v6.6)  If the crash occurred on the latest nightly builds (or compiling yourself from the latest source code), please let me know because that's unexpected.

The problem has been temporarily "fixed" in the latest development builds, but it requires disabling Tab key support.  A more complete fix is incoming soon.  I'll update this issue (and #172) when it lands.

**Comment by jpbro** [comment]
Hi Tanner - sorry my mistake. I did look at that error first, but since it mentioned an actual error message/code (and on my computer it just crashes - the difference between running compiled and in IDE I suppoes) I quickly dismissed it as a different issue (too quickly it would appear!). I tried the latest nightly build and there is no crash (but of course TAB is disabled as you mentioned). Sorry for the unnecessary duplicate report.

**Comment by tannerhelland** [comment]
No apology necessary!  You are *always* welcome to submit bug reports.  I really appreciate you taking the time to help me!

I feel bad I haven't correctly solved this issue yet, but it's hugely complicated, and it requires me finally replacing the last few pure-VB controls with custom-built user controls.  Once that's done, I won't need to rely on VB to handle tab order, and I can finally fix this "for good".

Thanks much for your patience, and thanks again for the bug report.

**Comment by jpbro** [comment]
No need to thank me :) thanks for all of your hard work on PhotoDemon, it's a fantastic piece of software!
