### ISSUE TITLE
BUG: Cross-Screen filter

### ISSUE THREAD

**Issue by audioglider** [tannerhelland/PhotoDemon#177]
The Cross-Screen filter is only rendering the mask instead of the composited image. Or there could just be a ghost in my machine.....

**Comment by tannerhelland** [comment]
Argh, my bad.  When I overhauled pdCompositor earlier this month, I tested it against a few effects and thought I hadn't broken anything, but Cross-Screen uses it in a weird way and I totally forgot to check.  So no ghosts in your machine, just my sloppy coding as usual!  :/  

Anyway, thanks much for catching this.  Hope the new version of the effect (from Oct 3) works a lot better than the old one.  I haven't tested a ton of images (this is my go-to, because it has just the right mix of highlights: http://images2.fanpop.com/images/photos/6200000/Tardis-in-Space-tardis-6289810-1280-768.jpg), so if you get poor results on your own images, please do let me know so I can refine the algorithm.

**Comment by tannerhelland** [comment]
Oops, forgot to mention the issue number in the commit.  Fixed by 7ab3eb9ab84cbc83ee46740a9fcce21dc58b248c.

**Comment by audioglider** [comment]
No problem, I didn't see it before either because I rarely use the effect. But the performance is much better than it was! I've had great results with every photo I've thrown at it.

**Comment by tannerhelland** [comment]
That's great to hear.  Thank you for the feedback.
