### ISSUE TITLE
[Batch processor] Always display error message "File not found" after removing a file on hdd from batch list

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#203]
**Steps to reproduce:**
1. Open PhotoDemon
2. Choose File->Batch process...
3. Click "Next" button in "Batch Process Wizard" dialog
4. Use drive select box and tree view of files and folders to select a folder containing images on your HDD
5. Click into a valid image in the list of files
6. Click "Add selected image(s) to batch list" button
7. Click into the added image in batch list
8. Click "Remove selected image(s)" button
**Expected result:** The image is removed from the batch list with no error message
**Actual result:** Display error message:
Unfornately, the image " could not be found.
If this image was originally located on removable media (DVD, USB drive, etc), please re-insert or re-attach the media and try again.
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:**
**Attachment:**
Screenshot:
![filenotfound](https://cloud.githubusercontent.com/assets/14866765/15389088/582f278a-1ddf-11e6-9285-fd738e1a3b2c.jpg)
Gif:
![stilldisplayerrormesswithfilesonhdd](https://cloud.githubusercontent.com/assets/14866765/15389099/6274b674-1ddf-11e6-854e-74f82bc633eb.gif)

**Comment by tannerhelland** [comment]
Hi @vhreal1302.  Thank you for this bug report.

The batch processor is not integrated with any of the nightly build changes since the previous stable release.  In fact, it is unlikely to work at all, and it must be significantly overhauled before the next release.  

It doesn't really make sense for me to work on the batch processor until work on the main program wraps up, so I typically postpone batch processor work until the very end of the development cycle.  (This way, I don't have to keep updating the batch processor against code that may just change again.)

None of this is clear to users who attempt to use nightly builds, and that is my fault.  I have now added a warning box to nightly builds when the batch processor is invoked.  I will update that warning (and this issue) once it's time to get the batch processor working again. 

Thank you for prompting me to do this!

**Comment by andrehunter** [comment]
photodemon error handler
