### ISSUE TITLE
[Edit metadata] Metadata changes do not affect Save button state

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#206]
**Steps to reproduce:**
1. Open PhotoDemon
2. Open an image
3. Choose Image->Metadata->Edit metadata...
4. Click on Exif in the first box
5. Change Image Description to something different
6. Close the image
7. Reopen the image to check its Image Description in metadata
**Expected result:** Image description is changed
**Actual result:** Image description is not changed
**Note** Similar issues happen with other meta details that users are allowed to change
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1557)
**Attachment:**
![unabletoeditmetadata](https://cloud.githubusercontent.com/assets/14866765/15426321/fa00d8fa-1eb7-11e6-86d3-df06e95b399e.gif)

**Comment by tannerhelland** [comment]
Hi @vhreal1302.  Metadata changes are like other non-destructive edits.  You need to save the file for the changes to take place.  (If you close the file without saving, the metadata changes will not be applied, by design.)

**Comment by vhreal1302** [comment]
The "save file" icon was still disable after I was done editing Image description, so I thought I could not save the change before I closed the image in step 6. But if I used the "Save as", the change was made in the new image. Are you refering to "save as" when you say that I need to save the file?

**Comment by tannerhelland** [comment]
Yes, "Save" or "Save As" are both fine, depending on which is available. 

The "Save" button may not be enabled after metadata editing for some complex reasons.  The "Save" button state is tied to the Undo engine, and the Undo engine works on a seemingly simple formula: "If the image has changed, create a new Undo point."  With metadata, this check is complicated because "if the image has changed" depends on the exported image format.  (e.g. for BMP a metadata change may not affect the image, so we don't need an Undo point, but for JPG that may not be the case.)

Because PD can't predict what export format a user may use, metadata doesn't play nicely with the Undo engine.  I have some ideas for improving this, but they're somewhat complicated to implement.

I can leave this issue open until I make a firm decision about how to handle Undo/Redo and metadata changes, so we can make sure that the Save button state enables intuitively after metadata changes are made.

**Comment by tannerhelland** [comment]
Just a note that I've adjusted the issue title to better describe the required fix.
