### ISSUE TITLE
[Save as] Save image as a .pnm file but a .ppm file is created and it is unable to save changes on this file

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#215]
**Steps to reproduce:**
1. Open PhotoDemon
2. Open an image
3. Save the image as a .pnm file
4. Close the new image created by saving as
5. Reopen the image closed in step 4
6. Add a text layer
7. Choose File->Save
**Expected result:** After step 3, a .pnm file is created and changes are saved after step 7
**Actual result:** After step 3, a .ppm file is created and after step 7, it is unable to save changes on this file
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1603)
**Attachment:**
![pnmtoppm](https://cloud.githubusercontent.com/assets/14866765/15533660/d185c710-228f-11e6-8a7a-eb79f89de627.gif)

**Comment by tannerhelland** [comment]
Okay, there are two issues at play here: one is a bug and I think the other is a misunderstanding.

I've fixed the issue where saving a PNM file, then reloading it, causes an unspecified error.  Thank you for reporting this!

As for the file extension changing, this is controlled by the option in the PNM export dialog called: "change file extension to match color model."

The whole class of portable image files (PBM, PFM, PGM, PNM, PPM) are strange because they are basically the same image format, but the file extension is supposed to change based on color depth.

If the "change file extension to match color model" option is selected, PhotoDemon will automatically figure out the "correct" file extension for the selected export options.  (e.g. "PBM" for monochrome images, "PGM" for grayscale images, etc.)  This is the preferred behavior, I think.

If the "change file extension to match color model" option is NOT selected, PhotoDemon will export a generic "PNM" file (this stands for "Portable aNymap").  PNM is not as well-supported as the older sub-formats, but that's how you would generate one anyway.

Hope that information helps!  (Once my coding work settles down, I hope to have time to write help files that explains issues like this... but for now it's a lot of trial and error, I'm afraid.)

**Comment by vhreal1302** [comment]
After unchecking option "change file extension to match color model", file extension of the image generated was .pnm as I expected and I started to understand what you explained here. Thank you for the information!
