### ISSUE TITLE
[Export options] Background color is not applied

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#217]
**Steps to reproduce:**
1. Open PhotoDemon
2. Open a .jpg image
3. Choose Image->Canvas size
4. Input width = 110%, height = 110%
5. Click on "Ok" button
6. Press Ctr + S
7. In "JPEG export options" dialog, in "basic" tab, choose a background color
8. Click on "Ok" button of "change color" dialog
9. Click on "Ok" button of "JPEG export options" dialog
**Expected result:** Transparency area is filled with background color chosen
**Actual result:** Transparency area is not filled with background color
**Note:** Silimars issues also happen with export dialogs of .tif, .ppm, .png, .bmp
![tiff](https://cloud.githubusercontent.com/assets/14866765/15563868/f2d53c5a-2336-11e6-9382-4fb50bee4fc9.jpg)
![ppm](https://cloud.githubusercontent.com/assets/14866765/15563870/f6121a96-2336-11e6-8657-75ed48214666.jpg)
![png](https://cloud.githubusercontent.com/assets/14866765/15563873/f8d432d2-2336-11e6-8c85-3635e892d691.jpg)
![bmp](https://cloud.githubusercontent.com/assets/14866765/15563874/fb94c7fc-2336-11e6-9d4b-8ca5ba485e23.jpg) 
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1607)
**Attachment:**
![bgcolornotapplied](https://cloud.githubusercontent.com/assets/14866765/15563604/48aaf280-2334-11e6-8e86-c1cd5f0f3618.gif)

**Comment by tannerhelland** [comment]
Hi @vhreal1302.  Apologies if I misunderstand your bug report, but this looks like correct behavior.

Settings from a Save File dialog will **never** affect the current on-screen image.  Save File settings only affect the exported file.  (Otherwise, things like saving to JPEG would slowly make the on-screen image look worse and worse, because the JPEG compression would erode the original image on each save.)

So when you set a background color in an export dialog, that background color will only be used to generate the saved file.  It will never affect the on-screen image.  (Additionally, the background color setting will only affect the saved file if your current save settings don't allow the file to store transparency.  For example, JPEG never allows transparency, obviously, but formats like TIFF or PNG will only use the background color if you forcibly save to a non-transparent color depth.)

I hope this information helps.  Please let me know if I misunderstood your bug report.  (I ran some tests just to be safe, and it looks like exported files are using the background color setting correctly.)

**Comment by vhreal1302** [comment]
I got it, this is not a bug. I'm sorry for the wrong report. Thank you for your detailed explanation.

**Comment by tannerhelland** [comment]
No need to apologize.  Even though it's not a bug, it is very helpful to know that program behavior like this is confusing.

I'm going to leave this bug report open while I brainstorm a better way to present this feature.  At the very least, I can add some logic to hide the "background color" option entirely if the current image doesn't contain transparency.  That will be a step in the right direction.
