### ISSUE TITLE
[Text layer] The slider does not disappear completely when users change antialiasing from Normal to None

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#229]
**Steps to reproduce:**
1. Open PhotoDemon
2. Click into text layer button T, change antialiasing from None to Normal
3. Change antialiasing from Normal to None 
**Expected result:** The slider disappears completely
**Actual result:** Only a part of the slider disappears
**Note:** There is no issue when users change antialiasing from Crisp to None
A similar issue happens when users change appearance of a selection tool from highlight to lightbox
![sliderdoesnotdisappear](https://cloud.githubusercontent.com/assets/14866765/15650406/8e878b44-26a2-11e6-9cae-176b97fd4367.jpg)
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1640)
**Attachment:**
![sliderdoesnotdisappear](https://cloud.githubusercontent.com/assets/14866765/15650457/e8e5542c-26a2-11e6-91ac-17be42966118.gif)

**Comment by tannerhelland** [comment]
Hi @vhreal1302.  Thank you for reporting this.  I can't reproduce this issue locally, but I will dig up an old PC this weekend and do some testing.  It's possible the issue is related to DWM (Desktop Window Manager - https://en.wikipedia.org/wiki/Windows_Aero) on Windows 7, but only if Aero Glass is disabled.  I'll see what I can find.
