### ISSUE TITLE
[Layers box] After turning off layers, turn off tool options make the focus changed from PhotoDemon's window to another

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#230]
**Steps to reproduce:**
1. Extract PhotoDemon's zip file to a folder
2. Open PhotoDemon
3. Click on button rectanguar selection ![rectangualrbutton](https://cloud.githubusercontent.com/assets/14866765/15652764/b003234a-26b2-11e6-970c-cb5935be4c14.jpg)
4. Uncheck Window->Layers
5. Uncheck Window->Tool options
**Expected result:** The tool options is turned off and the focus is still on PhotoDemon's window
**Actual result:** The focus is changed to another window behind PhotoDemon's window (The issue cannot happen when I record it so I do not have a video attached, I hope that you can still reproduce it.)
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1640)

**Comment by tannerhelland** [comment]
Hi @vhreal1302.  Thank you for reporting this.  Can you let me know if you still have this problem on build 1671 or later?  Thank you!

**Comment by vhreal1302** [comment]
The problem is solved on build 1671. By the way, is the tool ![toolpaint](https://cloud.githubusercontent.com/assets/14866765/15800111/56c95f6e-2a9b-11e6-90d8-33f352c30c50.jpg) being disabled or not? I cannot use it.

**Comment by tannerhelland** [comment]
Thank you for testing the new build.  When Windows 7 uses its "Basic" theme, there seem to be many strange issues like this.  I'm glad we're slowly finding and fixing them.

Also: the current "Paint Tool" icon is just a placeholder.  Developer builds have many placeholders like that, which I can use to see if layout and windowing code are working correctly.  I haven't actually implemented the paint tool code yet, however, so the "tool" does nothing at present.  I am trying to finish up the bulk of my User Interface work before adding new canvas tools.  (Otherwise, I just have re-do all their interfaces after new interface work is complete.)

Thanks!
