### ISSUE TITLE
Non-English characters in path raises "path not found" error

### ISSUE THREAD

**Issue by LemuelCushing** [tannerhelland/PhotoDemon#235]
Trying to open a file from a path with Hebrew characters causes the following error:
![image](https://user-images.githubusercontent.com/7855659/27760345-1db5b168-5e4e-11e7-965f-ee8b1f64a177.png)

**Comment by tannerhelland** [comment]
Hi Lemuel.  Thank you for reporting this bug.

Can I ask what version of PhotoDemon you're using?  PhotoDemon 6.6 has very limited Unicode support, but I would expect the latest nightly builds to work.  I will need to investigate differently depending on what version gave you the error.

**Comment by LemuelCushing** [comment]
Hi Tanner, thanks for the quick reply!

I was using 6.6, but I checked the nightly now and the problem is gone. Quite an overhaul! Guess I should have checked the nightly before posting.
My anti-virus (Kaspersky) flags the PhotoDemon.exe as a virus, for some reason, while 6.6 had no issues. Minor issue for me, but just FYI, in any case.

Thanks again, a superb piece of software!

**Comment by tannerhelland** [comment]
Whew, that's great news!  My favorite bug is an already-fixed one.  :D 

Nightly builds have some issues with virus scanners because as soon as one gets whitelisted, I release a new one with a different file signature.  It's a never-ending game of cat and mouse, I fear.  Once a new stable version is ready (hopefully not long now??), I'll contact the major AV companies and make sure we get whitelisted.

As a "thank you" for reporting this, I'd still like to add your name to the contributor list for the next release.  Am I okay to just use your GitHub alias and page, or would you like me to use another name+URL?

Thanks!

**Comment by LemuelCushing** [comment]
That'd be an honor! :) My GH ID would certainly work.
And if you ever need some feature tested, I'd be more than happy to assist. Not much of a programmer, but my day job does consist mostly of bug-hunting, so... 

And again, thank you! ;)
