### ISSUE TITLE
[Feature request] Undo / Redo inside tool windows

### ISSUE THREAD

**Issue by vatterspun** [tannerhelland/PhotoDemon#238]
I'm a huge fan of this program and just wanted to make some suggestions.

**Request:** Ability to undo (multiple back up) after modifying filter elements, as well as clicking the random and restore buttons.

**Why?**  Very often I make several changes and realize the best possible one was two or ten steps back.  I try to go back to the previous one and either get sort of close or not quite.  An undo process would save me a lot of grumbling. 

**How?** I'm thinking just a standard ctrl+z to back up.  If you wanted to get really fancy, ctrl+y could cycle forward again through the various changes.

**Comment by tannerhelland** [comment]
Hi vatterspun.  Thank you for the great suggestion.  This is definitely something I can look at for a future release.  

Since you've spent some time thinking about this, can you walk me through your concept for **when** a filter element should flag an "Undo point"?  For example, if a filter only has one controllable parameter, should it still support Undo/Redo?  How can we avoid generating too many Undo/Redo points, e.g. if a user clicks-and-holds one of the up/down buttons on a slider?  What about typing in a text box - every keypress is likely to be overkill (e.g. typing out "100" shouldn't create an Undo/Redo on "1", then "10", then "100"), so how can we determine which inputs are useful to a user, and which are just intermediary steps toward something else?

My initial thought is to rely on controls losing focus to generate Undo/Redo points - for example, when a user switches from one slider to another, flag the current setting as a viable Undo/Redo point.  But that wouldn't capture repeated changes made with the same slider.  Maybe that's okay?

**Comment by vatterspun** [comment]
Awesome, thanks for considering it.

I recognize the need to make sure that not every movement and shift is an undo point.  For mouse flags, I'd probably say whenever the mouse button is un-clicked (i.e. let go).  I think how you put it as "losing focus" makes a lot of sense.

I'm going to be honest that I didn't really think about the keypress angle, but I'd probably say every word, which is I think what Microsoft Word does.  I haven't done a lot of text edits to my images as I tend to use PD for editing (usually making darker) large images for desktop backgrounds.

**Comment by tannerhelland** [comment]
It has taken me a __very__ long time to get to this request, but yes, I'm finally tackling it.  Thank you for your eternal patience, @vatterspun!  

I've just committed new code that adds little Undo/Redo buttons to the "command bar" (as I call it) that sits at the bottom of every PhotoDemon adjustment and effect dialog.  These new buttons allow you to step forward and backward through changes to the current dialog, same as any other Undo/Redo buttons.

![undo_redo_tool_dialogs](https://user-images.githubusercontent.com/1930029/94067732-87ee5580-fdab-11ea-8b71-b24dc48100e5.png)

There were a lot of different ways to implement this feature, and after pondering it for several years (literally), I've chosen to go with the simplest mechanism I could: taking a "snapshot" of the current tool's settings roughly every second.  (This interval automatically extends if the window is doing heavy processing; this helps keep the UI fluid when previewing complex effects.)

When settings changes are detected, the command bar saves a "snapshot" of those settings, and the little Undo/Redo buttons are activated accordingly.  You can then use them to step through the auto-saved list of dialog changes.

I don't know if time-based snapshots are the "best" way to tackle this problem, but it has an enormous advantage for me - I don't have to manually edit every single effect and adjustment window to support Undo/Redo.  Instead, every tool window gets it "for free".

I obviously need to do a lot of testing to make sure this doesn't have any weird interactions with specific tools, but adding this feature early in 9.0's development cycle means I have plenty of time to test everything.

Feedback and/or bug reports are of course welcome, and thank you again to @vatterspun for this lovely idea.

**Comment by tannerhelland** [comment]
Thank you again for this suggestion, @vatterspun .  After many weeks of testing, I'm feeling more confident in the reliability of this feature.  I hope it meets the criteria of your original proposal!

I'm closing this issue for now, but if you encounter any issues with this "effect dialog" version of Undo/Redo, please let me know and I'll investigate.
