### ISSUE TITLE
msvbvm60.dll not found

### ISSUE THREAD

**Issue by ramoneeza** [tannerhelland/PhotoDemon#239]
When try to execute via network share. Silent error msvbvm60.dll not found abort program.

**Comment by vatterspun** [comment]
1. What's your setup?  WinXP?  Is the network drive mapped?

2. It's possible to download that DLL file to your local computer (it's freely available) or in your case a network drive.  Will it work then?

One place to get it: https://www.portablefreeware.com/downloads/msvbvm60.zip

**Comment by tannerhelland** [comment]
@ramoneeza, if this continues to give you trouble, please let me know.  Since it's been quite a few weeks without an update, however, I'm going to assume that you were able to work everything out.  

Thanks again for filing an issue, and please let me know if you run into any other problems with PhotoDemon.
