### ISSUE TITLE
Sluggish Accelerators

### ISSUE THREAD

**Issue by jpbro** [tannerhelland/PhotoDemon#243]
Hi Tanner,

Thanks for not only developing such a great piece of software, but also for releasing it free and open source. It's a real gem, and I'm glad I finally got around to cloning your wonderful program! 

There's one small Ux "hiccup" in PhotoDemon that I thought I'd try to address as any easy first foray into contributing back.

I've found using multiple accelerators in a row to be a bit sluggish. Most commonly for me, this would be a Ctrl+A (to select all), followed by a Ctrl+C to copy the selection to the clipboard. When I subsequently go to another program and press Ctrl+V (to paste) I would either get nothing or a stale copy from the clipboard (essentially the Ctrl+C wasn't being processed).

I traced this to the ctlAccelerator_Accelerator method, specifically the code that makes sure that multiple accelerator firings don't occur faster than the system keyboard delay. In most cases this is fine, but for situations where you might do 2 or more "quick-fire" accelerator combos, the current code is a bit too general as it doesn't differentiate between quick repeats of the same accelerator and quick repeats of different accelerators.

My fix looks like this:

`   ' Since Accelerators can be fired multiple times by accident.  Don't allow the user to press`
`   ' the same accelerator faster than the system keyboard delay (250ms at minimum, 1s at maximum).`
`    Static lastAccelerator As Double`
`    Static lastAcceleratorIndex As Long`
`       `
`    If lastAcceleratorIndex = nIndex Then`
`      ' The current accelerator is the same as the previous accelerator,`
`      ' So shortcircuit if we've received this message too quickly.`
`      If (Timer - lastAccelerator < getKeyboardDelay()) Then Exit Sub`
`    End If`
`    lastAcceleratorIndex = nIndex`

It tracks not only the last accelerator clock time, but also the last accelerator index.

I _think_ this is a good solution, but of course I defer to your superior expertise if you have a better idea. 

I would have issued a pull request, but because I have different system settings (DPI specifically I think) my VBP_FormMain.frm source is showing changes to a lot of control properties like Client*, Scale*, _Extent* that I'm not sure you would want to pull.

**Comment by jpbro** [comment]
It looks like I was working against the source for 6.1 with the above code. Not sure how I got that instead of the 7.0 code (I guess I forked the source a while back and when I tried to do a new clone it picked that instead of the latest source from your repo). :blush: 

The above code may not be applicable as a fix in the latest code. I'm now up-to-date source-wise, so I will dig in and see if A) this issue has already been resolved, and B) if not, find a solution for the latest code.

**Comment by jpbro** [comment]
I've found a possible solution for this issue against the latest 7.0 source, and I have created a pull request here: https://github.com/tannerhelland/PhotoDemon/pull/245

This is my first pull request here, so please let me know whether or not I'm going about things in the preferred manner. Thanks!

**Comment by jpbro** [comment]
This issue has been addressed by Tanner in the 7.2 development branch as per commit https://github.com/tannerhelland/PhotoDemon/commit/e3d276b4b28a896beaee1c3cdc7037c2e11ca728

**Comment by tannerhelland** [comment]
Hi @jpbro .  Thank you for the kind words.  You are a brave man to jump into PD's source code.  It is rarely easy to track down where a task actually occurs, so I'm impressed you figured out the source of this bug.  Thank you!

As mentioned at #245, I have manually merged your suggested fix in a separate commit to the new 7.2 branch (e3d276b4b28a896beaee1c3cdc7037c2e11ca728).  Hook procedures are a little messy in VB because we have to manually translate reported parameters into usable key events (https://msdn.microsoft.com/en-us/library/windows/desktop/ms644984%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396).  wParam actually contains the key code itself, while the "code" parameter just contains hook-specific info.  I moved your fix to a new location to avoid having to remember these low-level hook details in the future.  (I had to revisit MSDN just to make sure I had everything right!)

I use this complicated hook-based solution for hotkeys because PD intermixes a lot of system windows (like edit boxes) with regular VB windows as part of supporting Unicode everywhere.  Similarly, the main window is actually multiple forms "stitched" together at run-time, so I need a central hotkey handler that can handle events raised by multiple windows.  There are still imperfections - for example, if system edit boxes have focus, most hotkeys don't trigger.  This is correct behavior for something like Ctrl+C, because the edit box should handle that locally, but not okay for something like Ctrl+O which the edit box doesn't handle.  I don't have a great fix for this yet.

Anyway, I wanted to ask - with this patch, do you still find quickly-fired hotkeys too sluggish?  PD is currently set up to ignore hotkeys that occur while the system is busy processing, which can still cause missed hotkeys in a situation like Ctrl+A quickly followed by Ctrl+C, if the "Select All" operation is still processing when Ctrl+C is pressed.  (On that note, this isn't a fix, but if you just press Ctrl+C without pressing Ctrl+A, PD infers that you want a whole-image copy and it will silently assume the Ctrl+A part for you.  I'd still like to fix this bug but maybe that counts as a "temporary" fix!) 

I've looked at changing hotkey processing to a queue system where hotkeys are allowed to accumulate while the program is busy, and when an operation finishes, any hotkeys in the queue are then dealt with in the order they occurred.  If hotkeys are still sluggish for you (particularly compared to other software), I'll start investigating that as a more "comprehensive" fix to this issue.

**Comment by tannerhelland** [comment]
(sorry, reopening this issue momentarily for my own benefit, as I may have more work to do here)

**Comment by jpbro** [comment]
Sorry for closing the issue! I'll keep my dirty paws off of issues I open n your repository going forward and leave it to you to manage as you see fit :)

I must also apologize for mucking up the nCode/wParam stuff too. I should have done proper testing, but I was hungry for some glory and I rushed out my second "solution". I'll be more careful with future pull requests.

Re: how the changes are actually performing, I'll run some tests to see if there is noticeable improvement and report back soon.

Thanks for the detailed explanation of your approach too! I'll give some thought to the focused system control accelerator issue and let you know if I get any bright ideas.

PS: From my initial quick code spelunking, your code is easy to follow and things seem to be more or less where I'd expect them to be, and named how I would expect them to be named. So reports of my bravery may have been greatly exaggerated ;)

**Comment by jpbro** [comment]
The new approach is definitely an improvement. The problem still exists if I do a really fast Ctrl+A/Ctrl+C, but a slight delay captures the Ctrl+C correctly (whereas the same delay misses the Ctrl+C with the old code). Note that I'm testing this with just my fingers, so the delays won't be exactly the same in each test, but it definitely _feels_ better.

Would the missed rapid-fire accelerators have something to do with the fire timer delay perhaps? Maybe a solution would be to implement a queue of accelerators and fire them off FIFO?

**Comment by tannerhelland** [comment]
Thanks much for the follow-up info.  If things *feel* a bit better, we must be doing something right!  

It's entirely possible that the timer firing delay is related, but I'm with you - an accelerator queue is simply better way to handle this.  That would cover any/all sources of delays, regardless of where they arise.  I'll start knocking out a proper implementation instead of the hodge-podge thing I've got going now.

(Also, I'm really glad you brought up these keyboard issues now, because I'd love to have them working perfectly before allowing users to customize hotkeys.  That will introduce more variability than I could ever properly test, and a proper hotkey queue will make me feel much better.  Thanks again!)

**Comment by jpbro** [comment]
Hi Tanner, sorry if you've been getting weird pull requests from me...I'm trying to get your 7.2-release branch into my fork and failing miserably :(

I have knocked up a seemingly working queue approach based on your 7.2 code that I'm trying to get into my repo for you to have a look at. It may not be perfect, but it seems to be working quite well here.

I'll keep trying to figure out where I'm going wrong and get back to you with my implementation ASAP.Still getting used to working across multiple repos/forks/branches!

**Comment by jpbro** [comment]
OK I think I got things sorted finally, and my apologies for any extra noise you've been receiving re: pull requests.

My initial attempt at a queue-based solution for this issue is here: https://github.com/jpbro/PhotoDemon/blob/master/Controls/pdAccelerator.ctl

When an accelerator is received:

* If it is NOT a duplicate of the last received accelerator, and the fire time is NOT yet running/started, then the accelerator will be added to the live queue

* If it is NOT a duplicate of the last received accelerator, and the fire timer is running/started, then the accelerator will be added to the accumulator queue.

* If it IS a duplicate of the last received accelerator, but enough time has passed to warrant a re-queue, then one of the two above rules will be used.

* If it IS a duplicate of the last received accelerator, but not enough time has passed to warrant a re-queue, then the accelerator will be dropped. 

The fire timer now processes every accelerator in the live queue in FIFO order. Once it has finished processing the live queue, it swaps in the accumulator queue. 

If there are any accelerators in the accumulator queue then the fire timer will be restarted. Otherwise, the fire timer will remain disabled.

Potential issues:
* I'm new to working with the PhotoDemon source, so my approach may be sub-optimal or even poor! I defer to your expertise of course, and only hope that my code may point you to a proper solution.

* Maybe the fire timer can run too long if there are slow actions initiated by particular accelerators? Should we test for long running queue processing and short-circuit & restart the time to finish the rest?

* The queue poses problems for things like Ctrl+O that block the queue from processing, but still allow accelerators to accumulate. I've added a function call `CanIAccumulateAnAccelerator` that blocks the accumulation of accelerates when it returns False. Currently, I am just checking if the main form is the active window (if not, then a dialog is open and we really don't want to accumulate anything). This may be insufficient or even wrong, so I'd appreciate your input here.

* I don't know if I'm imaging it or not, put the first rapid-fire accelerator sequence seems to behave as before (sluggish). After that things get snappier.

* I've tested this one a fair bit, but user interaction styles vary widely so my confidence is not high that this is a final solution. I'm hopeful that it is another step in the right direction though.

**Comment by jpbro** [comment]
PS: regarding:

> I'm really glad you brought up these keyboard issues now, because I'd love to have them working perfectly before allowing users to customize hotkeys

It's my pleasure! I've been meaning to try to contribute back to this project for a while, but I just never found the time until now. I thought I picked an easy target for my first contribution, but as happens so often, looks can be deceiving!

**Comment by tannerhelland** [comment]
Jason, thank you so much for this!  I don't mind PR noise at all, I'm just excited to have a pull request to review.  :D  

I'll report back after I have a chance to take a closer look (probably later today).  Looking forward to it.

**Comment by jpbro** [comment]
Just to clarify - my earlier pull requests are bogus (I was trying to get your 7.2-release branch into my fork and I was failing miserably!). 

If you would like I can issue a correct pull request for my changes, or you can just review the following commit in my fork: https://github.com/jpbro/PhotoDemon/commit/c661aa8129fe205629640b5b340cd5616c4edfda

Let me know what you prefer.

PS: No rush on the review!

**Comment by tannerhelland** [comment]
Reviewing your commit sounds great to me.  I get so few PR's that I'm pretty new to them as well, so this probably keeps me from breaking anything in your repository!  (Maybe that's not possible?  idk)

I'm also trying to figure out whether it's worth the trouble to work across multiple branches, as I've never done it for PD in the past.  The 7.0 release was so complicated that I'm worried about missing critical bugs (and things like the OK/Cancel fix would be nice to backport into a bugfix release), and branches definitely help with that... but they also create some headaches in the meantime.  We'll see how I feel in a few weeks...

**Comment by jpbro** [comment]
OK, I've tried submitting a pull request for my queue-based accelerator handling modifications for your review. Hope that worked!

**Comment by jpbro** [comment]
Regarding the following earlier comment of mine:

> I don't know if I'm imagining it or not, put the first rapid-fire accelerator sequence seems to behave as before (sluggish). After that things get snappier.

I'm wasn't imagining it, there is clearly a problem with the second accelerator detection of a 2 accelerator rapid-fire sequence (e.g. Ctrl+A, Ctrl+C) and only on the first rapid-fire accelerator sequence after startup!

I've traced this to the `IsVirtualKeyDown` down test for the Ctrl key in `HandleActualKeypress`. It is returning False even though the Ctrl key is down. Not sure why yet, but I thought I report this here in case anyone else had any ideas.

**Comment by tannerhelland** [comment]
> I've traced this to the IsVirtualKeyDown down test for the Ctrl key in HandleActualKeypress. It is returning False even though the Ctrl key is down. Not sure why yet, but I thought I'd report this here in case anyone else had any ideas.

Excellent catch.  I'm not sure the reason for this, but let's rewrite the Ctrl/Alt/Shift tracking to use a better system anyway.  IsVirtualKeyDown really shouldn't be used at all; instead, the hook procedure itself can simply note when Ctrl/Alt/Shift are pressed/released (because it gets notified of all key state changes!), and it should store their state at module-level.  Then we can just grab those module-level values inside HandleActualKeypress(), rather than involving IsVirtualKeyDown at all.

I don't know if this will fix the problem, but if nothing else it will solve a (rare?) bug where the user is fast enough to release Ctrl/Alt/Shift in-between the hook procedure being initiated, and the keypress actually being evaluated by PD's code.

**Comment by jpbro** [comment]
Sounds good, shall I give it a go? I'm happy to, just wanted to check before we duplicate any effort.

**Comment by tannerhelland** [comment]
Apologies, looks like I committed it just moments after you asked!  I was adding it simultaneous to my comment and I should have said as much.  :frowning:

I've also slightly modified the CanIAccumulateAnAccelerator() check based on our conversation in the PR thread.  

...Is there anything I've forgotten?  I'm honestly surprised this went as well as it did.  Hooks have caused me all kinds of grief in the past but from what I can see, hotkeys seem to be working very well now.  Your accumulation code makes a huge difference!

**Comment by jpbro** [comment]
No problem! I was just trying to save you some time, you wrote almost the exact same code I would have :) Kind of surprised it went so well too, and glad I could be part of the solution :)

One little thing, and this might be a micro-optimization so feel free to tell me to go fly a kite, but right now every Ctrl/Alt/Shift keypress is hitting `CanIAccumulateAnAccelerator`, and if True then `CanIRaiseAnAcceleratorEvent`, and the whole `HandleActualKeypress` loop. Would it be worthwhile to check for those keys against wParam before passing them as potential accelerators?

**Comment by tannerhelland** [comment]
Yes, that would be worthwhile!  Thank you for the suggestion.  (Similarly, every keydown/keyup event is currently being processed twice due to transition events, as you can see if you put Debug.Print statements in the function.)

I'll get both of these issues fixed up and committed.  Thank you for the tip.

**Comment by tannerhelland** [comment]
Thank you again for your help with this, @jpbro.  I've submitted a [new 7.0.1 release](http://photodemon.org/1852/photodemon-7-0-1-release/) with all these fixes.  I'm very happy that all users can now have a better accelerator experience!
