### ISSUE TITLE
DefaultCancel for commandBar UserControl

### ISSUE THREAD

**Issue by jpbro** [tannerhelland/PhotoDemon#244]
I'm curious about the decision to set the DefaultCancel property of the commadBar UserControl to False. I assume there is a good reason, but I think the downside is that it hurts Ux a bit since you can't press Esc to cancel & close a dialog or Enter to perform the default action (click the OK button). I tend to use the keyboard a lot (particularly ESC to close a window).

**Comment by tannerhelland** [comment]
Hi @jpbro.  This is a great question.  For reasons similar to those mentioned in the "sluggish accelerator "issue, I have to lean on key hooking in PD because I constantly intermix system and VB windows in order to handle Unicode text input/output.  (For example, edit boxes in various controls are system windows forcibly attached to underlying VB controls; as such, they don't play nicely with built-in VB properties like Default or DefaultCancel.)

Originally, the DefaultCancel property *was* assigned to each command bar's Cancel button (and similarly, the Default property to its OK button), but this caused messy issues with various user control types.  For example, PD's custom dropdowns need to intercept Escape keypresses if the dropdown's list is open, so it can behave like a regular dropdown - but if a control in the same window is marked as DefaultCancel, VB eats the Escape keypress before the dropdown gets it, and instead closes the whole window.  Enter keypresses have similar issues.

I thought I had fixed this in 7.0 with a custom-built Enter/Esc handler, but on further testing, I'm finding plenty of edge-cases where Enter/Esc keys don't trigger OK/Cancel.  I clearly botched my fix.  (In particular, if none of a dialog's controls have been interacted with yet, Enter/Esc don't seem to trigger anything at all.  But clicking on any control seems to solve it?  Argh, what have I done this time.)

Right now, I honestly don't know how to fix this issue, so I'll do some homework and report back when I have a gameplan.  Thank you for bringing this to my attention!

**Comment by jpbro** [comment]
Thanks for the detailed response. I thought there was a good reason for it, and clearly there was. Don't beat yourself up over the fix not working, this stuff is a pain (and not particularly fun to test and fix). I'll try to put some time into finding a solution too.

I tend to favour the keyboard (which is why I noticed), but I think most users primarily use the mouse for interacting with the UI anyway so I don't think is a high-priority.

**Comment by tannerhelland** [comment]
Now that 7.0.1 has shipped, I'm *really* hoping this has been resolved across all dialogs.  If it ever gives you grief again, please let me know!  (And thank you again for reminding me to fix it. :D )
