### ISSUE TITLE
Remaining on Github?

### ISSUE THREAD

**Issue by vatterspun** [tannerhelland/PhotoDemon#264]
Just wanted to quickly address whether or not you're going to stick around GH post-acquisition?  Most of the projects I follow said something about this, so just wanted to check.  Thnx.

**Comment by tannerhelland** [comment]
Yes, PhotoDemon is staying on GitHub!

My personal $0.02 is that [fears about the Microsoft acquisition are overblown](https://arstechnica.com/gadgets/2018/06/everyone-complaining-about-microsoft-buying-github-needs-to-offer-a-better-solution/), and since GitHub was hemorrhaging money, I'm just glad to see that a potential long-term solution has been reached.  Microsoft is a better suitor than many other big companies, and since PhotoDemon is a Windows app, I've made peace with its future being somewhat tied to Microsoft's.

That said, one of the great thing about Git is that devs can always move their repositories to a new host in a matter of minutes, and I'm glad anyone unhappy with GitHub has that option.  More competition in this space is never a bad thing.

Thanks for checking in.  Hope you're doing well!

**Comment by Kroc** [comment]
Yeah, I think the fact that you can just `git push` to any other service and everything-is-there, means that people should not be so quick to 'abandon ship'. Microsoft have many of the largest repositories ever in Git, they are fully committed to making it work for them.

**Comment by vatterspun** [comment]
Thanks for the response.  While you can do a push, there are some things that cannot be easily moved off Github (such as this conversation) so do proceed with caution.

**Comment by tannerhelland** [comment]
> While you can do a push, there are some things that cannot be easily moved off Github (such as this conversation) so do proceed with caution.

Surprisingly, even this has been improved in recent years.  From [GitLab's migration documentation](https://docs.gitlab.com/ee/user/project/import/github.html), for example:

> The following aspects of a project are imported [from GitHub]:
> Repository description (GitLab.com & 7.7+)
> Git repository data (GitLab.com & 7.7+)
> **Issues (GitLab.com & 7.7+)**
> Pull requests (GitLab.com & 8.4+)
> Wiki pages (GitLab.com & 8.4+)
> Milestones (GitLab.com & 8.7+)
> Labels (GitLab.com & 8.7+)
> Release note descriptions (GitLab.com & 8.12+)
> Pull request review comments (GitLab.com & 10.2+)
> Regular issue and pull request comments

No matter the host, it's a great time to be a git user!
