### ISSUE TITLE
Apply History to Other Image/Record History as a Macro?

### ISSUE THREAD

**Issue by jpbro** [tannerhelland/PhotoDemon#265]
This is a feature request (again) - If I'm being a bug just let me know :)

I'll start with a bit of background and my common workflow:

I'm not a graphic designer, but I like to think I have a decent aesthetic when it comes to the way I process my images. Now that everyone has stopped laughing, my typical workflow is to load an image, play with some adjustments and effects, often using the "Edit > Fade" tool in between (a godsend that one is!), occasionally undoing and redoing until I finally get something I like the look of. In other words, there's not necessarily a series of purposeful, methodological steps involved. It's easy to lose track of what I have done, and sometimes I've even resorted to writing down steps in case I want to reproduce them!

Now PhotoDemon has an awesomely long "Undo History" and it got me thinking that it would be cool if you could do something like this:

While in the "Undo History" window, if we could right=click a history entry and get a menu of options like "Record Macro from this point" and/or "Replay History from this point on another image" then it would be easy to take our existing flailings that produced satisfactory results and apply those same steps to other images.

Just a thought for a "neat" and potentially unique enhancement - I haven't thought it through too much so there may be glaring holes in the idea (how to handle selection changes if images have different sizes perhaps?) - but I thought I'd mention to you in case it gives you some inspiration :)

**Comment by tannerhelland** [comment]
Thanks, @jpbro - this is an excellent idea!  (That's not a platitude, btw - it really *is* an excellent idea, and I'm excited by the possibilities!  You're not the only one who's resorted to writing steps down to remember them!!)

I've been working on code for "auto-recording" macros as the user works, but my goals were primarily selfish (insert sheepish face).  It would be *very* helpful for debugging if PD could spit out a macro of the user operations that led to a crash, because then the user could just send me the macro and I could repeat their steps locally to try and reproduce bugs.

I believe the same code would work here: PD should be reworked to *always* record user actions, so if the user wants to create a macro from two arbitrary Undo History points, we already have all the data we need.  (Macros are just XML strings, so assuming we're keeping track of all user actions, creating a new macro from the Undo History window should be as easy as "cutting out" the proper chunk of the XML string and saving it to file.)

I will try to knock this out as soon as I finish my current work on overhauling PD's auto-updater to work with the new photodemon.org server.

>  there may be glaring holes in the idea (how to handle selection changes if images have different sizes perhaps?)

If I remember correctly, PD should already handle this case okay.  Selections in macros are saved using relative coordinates, e.g. instead of storing "create a rectangle selection from [0, 0] to [100, 100]", they store "create a rectangle selection from [0%, 0%] to [20% of image width, 10% of image height]".  This allows them to auto-size when played back against a new image.

I think the only things that don't currently play nicely with macros are paint tools... but I should probably double-check just to be sure.

**Comment by jpbro** [comment]
Well that was impressive! I just gave the new "create from history" feature a quick test and it was intuitive and worked flawlessly. Bravo! 👏 

PS: Sorry again that I didn't get back to you sooner about your comments on this request - things have been hectic around here the past week or so.

**Comment by tannerhelland** [comment]
No need to apologize!  There's never a hurry when you're providing help for free.  :)

I'm just grateful this turned out to be a quick and simple addition.  (These things are so hard to predict - tasks that seem easy are often way harder, but every once in a while you get lucky and something that seems hard is actually easy!)

Note to self: in a perfect world, I'd probably prefer a horizontal timeline instead of two vertical lists.  If there's ever a magical time where I have nothing else to work on, I may look at creating a new user control specific to this window.

Thanks again for the great idea!
