### ISSUE TITLE
Cannot run after compiling

### ISSUE THREAD

**Issue by FreeVB** [tannerhelland/PhotoDemon#273]
The error occurred in Sub LoadPluginGroup

**Comment by tannerhelland** [comment]
Hi @FreeVB.  I need a lot more information to have any hope of understanding this error.  PhotoDemon compiles and runs perfectly across my test PCs, but it sounds like this may be an issue in a 3rd-party library.

If you can fill out a standard bug report template, or at least attach some debug logs (from the /Data/Debug folder where you run PhotoDemon) it would help a lot.  Thank you!

### Let's start with version information
 - PhotoDemon version from Help > About, e.g. "PhotoDemon 7.2 pre-alpha (build 500)"
 - Windows Version (e.g. "Windows 10")

### Please describe the bug
What problem did you encounter?

### Expected behavior
Please describe what *should* happen.  (This helps me know what a fix might look like.)

### How to reproduce the bug
The more detailed, the better!  If at all possible, a list works best, e.g.:
   1. Go to '...'
   2. Click on '....'
   3. Scroll down to '....'
   4. See error

### Debug logs
If you are using a nightly build, or if PhotoDemon has crashed more than once, it will automatically generate Debug Logs inside the PhotoDemon/Data/Debug folder.  If you can find the *most recent* debug log in this folder and copy+paste its contents into this bug report, that is a *huge* help.  

### Sample images and screenshots
If applicable, please attach the image file(s) that caused the bug.  Similarly, feel free to attach any screenshots that can help describe the problem.

**Comment by FreeVB** [comment]
Tested multiple Windows systems, it should not be a system problem, the test is normal in the IDE, the compiler does not display properly after the compilation, I found that the error is in the LoadPlugingroup here. LoadPlugingroup will not run afterwards.

PhotoDemon is the latest version just downloaded.

**Comment by FreeVB** [comment]
There is no problem with the compilation downloaded today, it may be caused by a plugin from the previous version.

**Comment by tannerhelland** [comment]
👍 That's great news, @FreeVB.  Thank you for letting me know that it's working.

I haven't updated any of the plugin files for [over a month](https://github.com/tannerhelland/PhotoDemon/tree/master/App/PhotoDemon/Plugins), so I'm not sure why they would change behavior so suddenly, but if you encounter the problem again, please let me know and I'll investigate further.
