### ISSUE TITLE
Failed to start because side-by-side configuration is incorrect

### ISSUE THREAD

**Issue by fly1062768879** [tannerhelland/PhotoDemon#274]
Run in the visual basic 6.0 without any problem, but it occurs this problem when making photodemon.exe and run it. Failed to start because side-by-side configuration is incorrect

**Comment by tannerhelland** [comment]
Hi @fly1062768879 .  Since this issue was quickly closed, I hope it means you solved your problem.

I have added a new [INSTALL.md](https://github.com/tannerhelland/PhotoDemon/blob/master/INSTALL.md) file to the repo to help explain the build process.  If you are not familiar with VB6, it may help.

Thanks!

**Comment by fly1062768879** [comment]
Thank you, Tanner.
The issue was quickly resolved because  an idea come to my mind. But it
failed again and again. Finally, I found the answer.
I really appreciate your responsibility and PhotoDemon is great tool.
Best Wishes.
