### ISSUE TITLE
Typography layer created with 0 height, trying to change crashes program

### ISSUE THREAD

**Issue by schneis** [tannerhelland/PhotoDemon#276]
OS/PD version:
Windows 7 x64, all updates applied
PhotoDemon release v7.0.1 & nightly build 1202

Issue:
I create an image and then try to create a Typography layer - layer is created with a 0px height, attempting to change the layer height to make the text visible crashes the program.

I am expecting the created Typography layer to not be a 0px height and resizing a 0px layer height should not crash the program.

Basic sample image which exhibits the problem is here:
[PD-crash-sample image.zip](https://github.com/tannerhelland/PhotoDemon/files/3439499/PD-crash-sample.image.zip)
(This is just a stripped down sample image - I keep running into this problem over & over with different images that I work on ... sometimes I can beat on it long enough to work, usually I have to start again from scratch.)

Opening the sample image & attempting to create a Typography layer exhibits the problem (using fresh downloads of both PD versions listed).

Just open the image, click on the Typography tool, then click on the image - a layer is created with a 0px height.  Click on the Move & Resize tool shows that they layer is 0px tall, trying to enter a height for the layer crashes the program.

Debug log is attached:
[DebugReport_1.log](https://github.com/tannerhelland/PhotoDemon/files/3439497/DebugReport_1.log)

**Comment by tannerhelland** [comment]
Thank you so much for catching this bug, @schneis.  I thought I had implemented extensive failsafes against zero-dimension layers, but a typo in a critical code section was incorrectly comparing new layer height against old layer **width** (instead of old layer **height**).  This incredibly stupid mistake could indeed lead to zero-sized layers on images with identical width and height values, when a new text or typography layer was created by clicking instead of click-dragging to a custom layer size.

Many apologies for the hassle this caused you, and thank you again for catching and reporting it!
