### ISSUE TITLE
Animated GIF import/export support

### ISSUE THREAD

**Issue by ruxia-TJY** [tannerhelland/PhotoDemon#278]
I'm always frustrated when I want to see a GIF animation, because when I use PhotoDemon to open a GIF animation, it's just a static image. I'd love to see an animation even if it's not editable when I open the GIF animation.

**Comment by tannerhelland** [comment]
Hi @ruxia-TJY.  Thank you for this suggestion.

Can you elaborate a bit for me, or perhaps share an example of another photo editor that animates incoming GIF files?

Animation is far outside PhotoDemon's current purview, but if other photo editors handle animated GIFs better than PD does, I'd be interesting in examining what they do and trying my best to bring PD up to their standards.

Thank you!

**Comment by jpbro** [comment]
IMHO animating a GIF in PD is really outside the scope of the software - I think of PD as an editing tool more than a viewing tool (like say Irfanview). That said, I could see a use for PD to possibly "burst" animated GIFs into their individual frames when opening them, or perhaps show a frame "picker" window on open to allow the user to select individual frames to rip out of an animated GIF into separate images in PD for editing. 

It could also be useful to save all currently opened images into a single animated GIF file. Just my 2 cents :)

**Comment by ruxia-TJY** [comment]
> I'm always frustrated when I want to see a GIF animation, because when I use PhotoDemon to open a GIF animation, it's just a static image. I'd love to see an animation even if it's not editable when I open the GIF animation.

I'm sorry for the misunderstanding that may arise in using the translator. I think using pictures may be more able to express my meaning. So I created a test library in github, and using. MD files might make my meaning clearer. The link is https://github.com/ruxia-TJY/Test/, which I will delete in seven days. And I sent a GIF attachment as an example.![1](https://user-images.githubusercontent.com/49090048/62478529-e76f5780-b7dd-11e9-8c58-712c628a3ca2.gif)

**Comment by ruxia-TJY** [comment]
> Hi @ruxia-TJY.  Thank you for this suggestion.
> Can you elaborate a bit for me, or perhaps share an example of another photo editor that animates incoming GIF files?
> Animation is far outside PhotoDemon's current purview, but if other photo editors handle animated GIFs better than PD does, I'd be interesting in examining what they do and trying my best to bring PD up to their standards.
> Thank you!

I'm sorry for the misunderstanding that may arise in using the translator. I think using pictures may be more able to express my meaning. So I created a test library in github, and using. MD files might make my meaning clearer. The link is https://github.com/ruxia-TJY/Test/, which I will delete in seven days. And I sent a GIF attachment as an example.

![1](https://user-images.githubusercontent.com/49090048/62479328-ca3b8880-b7df-11e9-8ba8-892a55ba1ad5.gif)

**Comment by tannerhelland** [comment]
Thank you, @jpbro and @ruxia-TJY .  The added discussion and pictures help a ton!  

Funny story - the PhotoDemon 6.0 release group imports animated GIFs as layered images (with each frame in its own layer).  But these versions lacked the ability to *export* layered images as animated gifs.  (Export is complicated, as GIFs have a ton of options like frame time, disposal methods, global vs custom palettes, etc.)  So at the request of users, I dropped animated gif import support in 7.0, and switched to just loading the first frame in the file.

The code still exists to import an animated gif as layers, but export support still needs to be tackled.  I think it's doable - it will just take some research and study on my part, as there a lot of UI considerations (so the user can do things like specify frame times for each frame in the exported gif), and any number of technical problems involved in assembling gif frames, since they are very limited in both color and transparency support.  Palette engine work in the current alpha builds could help with this, however.

A separate timeline control is a different, perhaps out-of-scope project, but I might be able to add something like a context-sensitive "play" button to the "overview" panel on the right side.  I will give this some thought.

I also like the idea of providing an easy way to split layers out into individual images, or the reverse (merge multiple open images into a single layered image).  This would allow users to import/export animated gifs in multiple ways.

I will follow this post with a concrete list of tasks, which I can update as I go.

Thank you again for the discussion and helpful resources!

**Comment by tannerhelland** [comment]
TODO LIST:

- [ ] Add easy way to "show only this layer" or "hide all layers but this one"
- [ ] Add shortcut for splitting layers into separate images, or merging separate images into a single layered image
- [ ] Reinstate import for animated-gif-as-layers
- [ ] Write new code for importing and storing GIF-specific animation metadata, especially frame times
- [ ] (optionally) provide a dialog when importing animated gifs, to allow the user to import only selected frames (or all frames) - note that this option will need to be suspended during batch processing
- [ ] Add support for exporting a layered image as an animated gif
- [ ] Mockup an "export animated gif" dialog, which needs a lot of options (GIMP could be helpful here, as it supports animated-gif-as-layers import and export) - note also that it needs to be smart about reusing metadata, like gif frame times, if the image was originally imported from an animated gif file
- [ ] Investigate options for previewing animated gifs - maybe use the navigator window on the right panel?

**Comment by jpbro** [comment]
@tannerhelland - I'm glad I could provide a little bit of inspiration, although I guess I just gave you more work to do, sorry! 😱 

I can see how merging multiple images could be a thorny issue with respect to the image sizes...Just thinking out loud here: Can an animated GIF change size while animating? I don't recall ever seeing one do that, and if it's not possible, I would expect that the fact that the image frames are all layers in the same image should be OK, no? If any layer is too large for the overall image canvas it will be cropped anyway (but you should still be allowed drag the layer around to position it within the image in that case). 

Anyway once again, awesome work on this, it's pretty darn slick 😄

**Comment by tannerhelland** [comment]
> Can an animated GIF change size while animating?

Surprisingly, some testing shows that it can! (Despite this being against the GIF spec, ha.)  I learned something new today.

Different browsers seem to handle this differently, though, so it's probably not a usable "feature" - looks like Firefox will increase the size of the GIF as a whole as it encounters larger frames, while other browsers crop off anything larger than the first frame.  Alas.

Either way, I've reworked PD's little animation previews to no longer assume that all layers/frames are the same size.  They should always grab a correct frame preview now.  One problem down!

This makes me think that it would be useful to provide an option dialog when merging multiple images into one multi-layered image, though - like where to align the new layers (presumably some combination of right/left/center and top/bottom/center, I think?).  And it could be nice to automatically resize incoming layers to "fit" inside the same image area.  I'll give this some thought.

> Anyway once again, awesome work on this, it's pretty darn slick

Thank you.  🙏  This has been a fun little project.  I'm excited to get animated PNGs working too.

**Comment by jpbro** [comment]
> Surprisingly, some testing shows that it can! (Despite this being against the GIF spec, ha.) I learned something new today.

Yikes! I guess I shouldn't be surprised, but I am!

> Either way, I've reworked PD's little animation previews to no longer assume that all layers/frames are the same size. They should always grab a correct frame preview now. One problem down!

👍 

> This makes me think that it would be useful to provide an option dialog when merging multiple images into one multi-layered image, though - like where to align the new layers (presumably some combination of right/left/center and top/bottom/center, I think?). And it could be nice to automatically resize incoming layers to "fit" inside the same image area. I'll give this some thought.

This make sense - if you assume anything here and try to automate/simplify the process, I'm sure it will mean an issue gets opened in the future where someone wants to do things a different way. Giving users the choice to align the new layers at different common anchor points and also having a "fit to canvas" option would cover the vast majority of use cases. As a final optional step, users can nudge any layers around a bit to get pixel-perfect crops if necessary once they're imported/merged.

**Comment by tannerhelland** [comment]
With animated PNG support fully complete, I think I'm finally ready to mark this issue RESOLVED.  

@ruxia-TJY - if you have any additional feedback on the new animated GIF features, please let me know.  Otherwise, thank you again for suggesting this improvement.

Just for fun, here's a copy of the original animation you provided, but converted to an animated PNG.  It's about 30% smaller than the GIF version, when saved using PhotoDemon's new File > Export > Animated PNG tool:

![animation](https://user-images.githubusercontent.com/1930029/64668818-50b93a80-d41c-11e9-948f-54009f463294.png)

Maybe something to consider for future animation work?

Thank you again, as always, to @jpbro for tons of valuable feedback!  I already find myself relying on the new Layer <> Image conversion tools, and I'm very grateful this issue led to some seemingly-unrelated-but-surprisingly-useful new additions to the project.

🙏 👍
