### ISSUE TITLE
[BUG] - (Polygon Selection crash app)

### ISSUE THREAD

**Issue by Jonney3099** [tannerhelland/PhotoDemon#284]
On Polygon selection, if I am fast clicking to make polygon, app crashed.

**Comment by tannerhelland** [comment]
Hi @Jonney3099 .  Thank you for filing a bug report!

Can you tell me what version of PhotoDemon you're using?  (Also, is there an easy way for you to capture a video of the crash?)

I ask because I've tried re-creating the problem in the latest nightly build but so far I've been unable to do it.  Thank you in advance for any additional details you can provide.

**Comment by Jonney3099** [comment]
I tested few version on IDE or exe, all crashed. The latest is 6/Dec/2019 build. OS are 32 bit Win10 and 64 bits win10.

**Comment by Jonney3099** [comment]
OK. I am going to debug a bit.
In "Friend Sub SetAdditionalCoordinates", error raise at  i = 0, m_NumOfPolyonPoints = 16:
     m_PolygonPoints(i).x = m_PolygonPointsBackup(i).x + (x - m_MoveXDist)
     m_PolygonPointsBackup(i).x =<Subscript out of range> 

If I am carefully SLOW clicking to make polygon selection, there's no crash for most of cases. But If am speeding up, PD will crash. 

Edited:
Good news is that I tested version in Jan. 2017, there's no crash.

**Comment by tannerhelland** [comment]
Thank you for the additional details, @Jonney3099 !  They are very helpful.

I will try to upload a fix for this soon.

**Comment by Jonney3099** [comment]
Well done! Crash has disappeared.

**Comment by tannerhelland** [comment]
Thank you so much, @Jonney3099 !  I really appreciate you reporting this bug and doing so much follow-up testing.  That made this issue so much easier for me to fix.  (Sorry that it took me some time to solve it.)

Best wishes for a happy holiday season!
