### ISSUE TITLE
Bug: Small canvas still shows full image in preview window (low priority)

### ISSUE THREAD

**Issue by vatterspun** [tannerhelland/PhotoDemon#290]
Setup: Win10x64 / PhotoDemon v7.0.1 

Steps:

1. Find a large image on your machine (around 1200x2000)
2. Open a "New" image that's a much smaller canvas (say 600x800
3. Drag-and-drop the large image into the PhootoDemon window
4. The result will automatically be cropped at the top-right corner
5. Select any transform function

Defect:

* Preview image is the large image from step 1.

Expected result:

* Image appears as it does live on the smaller canvas

Other notes:

* I'm also sometimes seeing the wrong preview window with multiple images open, but that's intermittent.

Screencap: https://i.imgur.com/GC4QZRG.png (NOTE: the preview image is in black and white but that's not relevent to my issue.)

**Comment by tannerhelland** [comment]
Hello @vatterspun!  I hope you are doing well during this weird and tense time.  (I am currently quarantined at home with a toddler, which is unfortunately not ideal for coding productivity... alas.)

Let me provide a quick explanation for the behavior you're seeing, and some small changes I have made to clarify why PhotoDemon does this.

When you add a new layer that is larger than the current canvas, PhotoDemon does *not* crop the layer.  Instead, it leaves the layer at its original size.  This non-destructive behavior is a major feature of the program, as it allows you to change the portion of the layer that is currently visible **at any time** (even after applying effects and adjustments!).

After adding a new layer to the image, you can position it however you want within the canvas by switching to the move tool (the blue arrows).  To make this more apparent, I've just changed the program to automatically select the move tool after dragging a new layer onto the canvas.  (This was already happening when Pasting a new layer, so it was good to match the behavior when Dragging in a new layer, too.)

If you apply effects or adjustments to that layer and later decide to reposition it, no problem!  Those effects and adjustments are always applied to the entire layer (even the off-canvas bits), which is why you see the full layer in the adjustment and effect preview screens.  

If you are absolutely certain the layer will not be moved in the future, and you want to forcibly crop it to the current image size, simply click the `Layer > Crop > Fit to canvas` menu.  (This may only be available in nightly builds; I don't remember if the last stable build included it, sorry!)  

That command will forcibly crop the layer and discard any pixels that lie off-canvas.  Note that the discarded pixels cannot be returned (except by Undo-ing back to that point in the image history).

Hope this helps!

(I will also keep an eye out for *"seeing the wrong preview window with multiple images open"*.  I'll let you know if I can reproduce it.)

**Comment by tannerhelland** [comment]
Hi @vatterspun.  I'm doing some cleaning up of PhotoDemon's issue collection today.  It's been over a year since this issue was last touched, and I'm hoping my last explanation (above) helped explain why PhotoDemon doesn't auto-crop newly added layers in an image, and why preview windows show the full layer instead of just the on-screen portion.

If you have further feedback, please let me know!  I'm happy to revisit if this still isn't working as intended.
