### ISSUE TITLE
image resize with 2 layers causes immediate crash

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#292]
### Version information
 - PhotoDemon nightly version (  the one before and the last one you just updated)
 -  "Windows 10" 

### Describe the bug
with two layers :  'resize image' menu > crash  suddenly, and image "resize content-aware" or "layer resize content aware" produces very bad distorsions of the image .
### How to reproduce the bug
The more detailed, the better!  If at all possible, a list works best, e.g.:
   1. open an image 1200x1500px
   2. open another image 800x1200px as a layer
   3. resize image > no progress bar , then crash.

[DebugReport_2.log](https://github.com/tannerhelland/PhotoDemon/files/4435229/DebugReport_2.log)
![01 before resize content aware](https://user-images.githubusercontent.com/62914748/78512328-ea26b000-77a3-11ea-9528-ad0dc3b3c64d.JPG)
![02 after resize content aware](https://user-images.githubusercontent.com/62914748/78512334-eeeb6400-77a3-11ea-9014-c9eb87b77ee7.JPG)

I am a french teacher , I found your software two weeks ago , it is very smart , well done and easy to use for everybody and especially for my  11-16 years old students . I have to make them discover how to work on images on a computer.  So , i have began to work on  a better french translation than google does, i'll send it soon .    Thanks a lot !.

**Comment by tannerhelland** [comment]
Hello @mizka76.  Thank you very much for your detailed bug report!

I believe I have corrected both issues.  The causes were not what I first expected, for example, the Image > Resize crash was caused by a mistake on my end in mistaken use of "." in a version string, to represent the decimal separator - this was causing a crash in locales like yours, where "," must be used.  (My apologies for this carelessness!)

It makes me very happy that you are able to use the software with your students, especially at this difficult time where schools are so disrupted by the ongoing pandemic.  Thank you for your kind words.  I would love to have an improved and updated French translation for the software if you are able!  I am very close to a new 8.0 release, so if you can update the language files supplied in the latest nightly builds, that would be wonderful.  There is a small instruction file for translations in the App/PhotoDemon/Languages folder, with the neame "README FOR TRANSLATORS.txt" if it is helpful.

I am also happy to add your name to the Contributor list.  Please let me know what name and/or URL you would like me to use, and I will get them added right away.  Perhaps your students will be extra impressed if they see you are a contributing author to the software.  :)

Kind regards and best wishes at this strange and difficult time.
