### ISSUE TITLE
translation in french

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#294]
i do my best , hope you enjoy it !

( it was the first time I try to translate, at the end,  i used the software Sublime Text,with Photodemon aside, so I could see what action exactly the words describes)  

language file   in french.xml 
in the french menu "Image->rotation" I cannot change  "180" to "rotation de 180°"
though there is a line in the french xml.file, but none refers to this in the master.xml file

in french xml:
5942<phrase>
5943<original>Rotate 180</original>
5944<translation>Rotation de 180°</translation>
5945</phrase>

though I don't have any knowledge in programing or coding i think it probably miss something  like this , at this place , i think .
in master xml : 
5908<phrase>
5909<original>Rotate 180</original>
5910<translation></translation>
5911</phrase>
I hope it helps. 
[French.zip](https://github.com/tannerhelland/PhotoDemon/files/4452887/French.zip)

**Comment by tannerhelland** [comment]
Hello @mizka76!  Thank you so much for this work.  🙏  I am very excited to have an improved French translation for the software!  I have added your work to the latest nightly builds.

> in the french menu "Image->rotation" I cannot change "180" to "rotation de 180°"

This is an interesting challenge for me to try and solve.

An automated tool produces the master translation list for PhotoDemon.  The tool is set to ignore numbers; otherwise, it would try to translate all numbers in the project, which would make translation files much larger - with numbers that don't actually need translating between languages!

This is why in the Image > Rotate menu, PhotoDemon does not currently attempt to translate the plain number of "180".

I will put some thought into how I might solve this.  Thank you for bringing it to my attention.

...I now have a small favor to ask.  I am very close to releasing a new stable build "version 8.0".  The new build will come from the current PhotoDemon nightly builds.

There are 14 missing translations in the current `App/PhotoDemon/Languages/French.xml` file included with the latest nightly build.  If you could do a quick search for empty translations (search for `<translation></translation>`) and fill them in, I will be able to ship a 100% complete French translation which would be a dream come true.

Thank you so much!

**Comment by mizka76** [comment]
hello ! 
here the update for the french langage !


[French updated.zip](https://github.com/tannerhelland/PhotoDemon/files/4547469/French.updated.zip)

**Comment by mizka76** [comment]
hello again, 
about the "rotate image 180" ... ok, i think i understand your explanations about this, but, i don't understand this :  it is possible to translate for the layer menu "rotate layer 180" for each langage file, and this  is not possible only for the image menu , logically if both entries ( layer , image) have 180 or numbers like 90° they should be both translated or not at all . ??

**Comment by tannerhelland** [comment]
I apologize that I forgot to add an updated comment to this issue!  

As of the previous commit (April 28), translators **can** add a degree symbol to all rotate text in the project.

Previously, there was no translation for `180` because the localization engine doesn't save numbers to localization files (and the menu read `Image > Rotate > 180`).  

I have updated the menu to read `Image > Rotate > Rotate 180`, so `Rotate 180` is now available in all translation files as a phrase that can be edited at will.  👍
