### ISSUE TITLE
[BUG] - Incorrect version shown?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [tannerhelland/PhotoDemon#296]
Not sure this is a bug or intentional since it's Alpha, but thought I'd throw it out there just in case no one was already aware, the versions don't match. This has an effect when trying to check for updates (even if just checking for new Alpha version updates).

![image](https://user-images.githubusercontent.com/39491297/80084529-998db180-851c-11ea-8dc5-276e64dc19c3.png)

**Comment by tannerhelland** [comment]
Hi @YouveGotMeowxy .  Thanks for reporting this!

This behavior is currently intentional.

[Like other open-source projects](https://stackoverflow.com/questions/1266411/which-open-source-projects-use-odd-unstable-even-stable-style-of-versioning) PhotoDemon uses an odd-unstable / even-stable version numbering scheme.

So any version ending in an odd number (e.g. 7.1, 7.3, etc) is a development branch for the next even-numbered stable release (e.g. 7.9 -> 8.0).  I hope to release a stable 8.9 build in the coming days, so the current nightly builds are labeled with a "7.9" version.

Hope that helps!
