### ISSUE TITLE
Working with .ICO files

### ISSUE THREAD

**Issue by g-busch** [tannerhelland/PhotoDemon#300]
I've been using the latest PhotoDemon nightly for creating transparent Windows icons. It's very good for that, but I still need to save them as PNG files, since saving in ICO format isn't supported. I'd like to suggest that it be supported in future versions.

Thanks!

**Comment by g-busch** [comment]
I forgot to mention that I've been converting those PNG files into ICO files with a different imaging program.

**Comment by tannerhelland** [comment]
Hello @g-busch !  Thank you for this feature request.  It is an excellent suggestion.

I have nearly tackled full ICO support in PhotoDemon a few different times over the years, but I did not know if anyone besides me would use it.  So I kept putting it off in favor of other tasks.

(Recently I had to do some work on PhotoDemon's application icon, and I ended up using GIMP for the task.  I was a little embarrassed that PhotoDemon couldn't do this on its own.  😨 )

Knowing that others could use this feature gives me newfound motivation.  Can you let me know a little more about what specific ICO features you need?  Are you simply saving a single standalone image as an ICO file?  

I ask because ICO files are capable of storing many different embedded icons at different sizes and color-depths.  This makes them considerably more complex than e.g. a JPEG or PNG.  (In fact, they're more like Photoshop PSD files, with many layers inside a single file.)

If you don't need multi-icon support, I can add basic ICO export over the next few days (time permitting).  Full support for multiple embedded icons is a larger task and would take me at least several weeks.

Also, if you don't mind letting me know what other software you've used that handles ICO files well, that is a huge help.  It's extremely useful to study other developer's approaches before embarking on my own.

Thanks in advance!

**Comment by g-busch** [comment]
Thanks for the response, Tanner. I replied by e-mail, but may have messed up the address, so here it is again:

No, I don't use embedded icons, just standalone .ICO files. One of the apps I've used for that was the Greenfish Icon Editor. It has the added ability to extract icons from .EXE and .DLL files, as well as to change them, although that can corrupt some executables. I even used it in the past to change PhotoDemon's icon. It worked on the nightly builds, but corrupted the stable one. The trouble with the Greenfish editor is its lack of a resize option, and a rather awkward crop function. You have to activate that tool first, then select the area with the mouse. It crops immediately when you let go, and if you don't get it right, you have to start over again, because there's no way of adjusting the selection.

Another application I've used that can create and save .ICO files is an editor called StylePix. I've used that at times, but it lacks some important features, and I don't want to use a whole collection of image editors to carry out tasks that a single image editor could handle on its own. My default image viewer (XnView Classic) can do some basic editing, but the many adjustments in PhotoDemon are far more accurate and flexible than in XnView. For example, XnView's straightening tool doesn't include retaining the aspect ratio when autocropping. It has a sharpening tool, but no unsharp mask, and the color balance controls are very limited.

Before I forget, I really appreciate the inclusion of the cloning tool. Are you planning on adding a healing brush, as well? Not critical, however, as the cloning tool has options that can often produce the same effect.

**Comment by tannerhelland** [comment]
Thank you for the detailed explanation, @g-busch!  It's a huge help to know concrete workflow details related to a feature request.  I will take a look at the software you mentioned to get a better idea for how PhotoDemon's icon workflow may work.

I am also happy to add you to the contributor list for the next release - just let me know what name and (optional) URL you'd like me to use.

I've just finished work on a homebrew ICO importer for PhotoDemon.  The new importer is now available in the latest nightly builds.

I am using this new importer to dissect various ICO files I've found online.  The ICO format is so old that many details in [the original spec](https://docs.microsoft.com/en-us/previous-versions/ms997538(v=msdn.10)?redirectedfrom=MSDN) (last updated in 1995!) are no longer valid.  Modern icons can be 768x768 or larger (the spec maxes out at 48x48), and embedded icons are no longer just Windows bitmap entries - they can actually be embedded PNG files, too.  

The 30+ year history of ICO files has made this one of those features where I just kinda have to study what "everyone else" is doing, and ensure that PhotoDemon follows the same general practices.  If any of the icon files you've produced no longer load into PhotoDemon, please let me know so I can get it fixed.

Next, I'm tackling icon exporting.  The technical aspects of this are straightforward.  As usual, it's the UI that will be difficult.  Icons have [a bunch of different requirements](https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-icons) depending on where/how you intend to use them, so PD needs to provide a straightforward UI for producing many sub-icons in a file from one or more source layers.  I don't have a current ETA for getting the export feature up-and-running, but I hope to wrap it up this month (fingers crossed).

I will post here when I have something new to show.

> Are you planning on adding a healing brush, as well?

Yes.  Someday.  :)  

Right now my primary effort is getting a new stable release out the door.  I was about ready to ship PhotoDemon 8.0 until this icon feature caught my attention.  Greatly improved file format support was a big emphasis for this release cycle, and current nightly builds support many new file formats relative to the last stable build (Photoshop PSD, OpenRaster ORA, HEIF, animated PNG and GIF).  I've written a ton of import/export code to support all those different formats, so I think it makes sense to fix ICO support too before releasing PhotoDemon 8.0. 

Once 8.0 is out the door, a healing brush is high on my to-do list.

**Comment by g-busch** [comment]
Well, I haven't encountered a single ICO file that has failed to open in PhotoDemon, and without exception I can also resize them, make changes to the individual objects that are layered over the transparent background, and save the files back in PNG format. XnView converts them to ICOs quickly and easily, so that's what I currently use.

Of course, PhotoDemon loads ICOs containing embedded images as single images, but as I mentioned earlier, that's not important for what I do. What I did notice is this: I loaded an ICO that I know has embedded images into XnView and it came up as a 256x256 image. When I loaded the same file into PhotoDemon, it came up as 48x48. I guess this is conforming to the old original specification, but this happens to be the size I usually use, anyway. Most of my desktop icons are that size, and if they happen to be a bit bigger or smaller, Windows always scales them to fit.

For the contributor list, feel free to use my real name, Gerry Busch. As for my URL, http://gbusch.altervista.org. the site is unrelated to programming or graphic design, as it contains nothing but the scores and MP3s of my music compositions. I know very little about coding, having stopped writing useless little programs in BASIC after the early 90s. The only code I deal with nowadays is for batch files, or the CSS and HTML that I use on my website.

Did that first e-mail reply I sent arrive in the right place? When I went to reply, the address displayed in the To address field was <reply+APOLIBANLY4BCAXUPUOAHC54YWJ6FEVBNHHCI6QEMU@reply.github.com>,  which certainly didn't look right!

**Comment by g-busch** [comment]
Just wanted to let you know that I've tested the new icon importer and it works flawlessly. In fact, so does everything else in the latest nightly build.

**Comment by g-busch** [comment]
Tanner, on portablefreeware.com I just discovered a tiny program that can convert PNG files to ICO, and embed several image sizes in the process. The program is completely portable, and consists of a standalone EXE less than 400 kb in size. It may give you some ideas for your exporter. The program can be downloaded at https://www.carifred.com/quick_any2ico .

Gerry

**Comment by tannerhelland** [comment]
Thank you for the follow-up info, @g-busch!  (And I like your new user icon 👍 )

> Of course, PhotoDemon loads ICOs containing embedded images as single images, but as I mentioned earlier, that's not important for what I do. What I did notice is this: I loaded an ICO that I know has embedded images into XnView and it came up as a 256x256 image. When I loaded the same file into PhotoDemon, it came up as 48x48.

Before, PhotoDemon used a 3rd-party library for loading ICO files.  By default, only the first frame in an icon file was being retrieved; any others were ignored.

You've probably noticed this already, but PhotoDemon's new homebrew ICO engine loads all embedded icon frames into their own layer(s).  By default, the largest + highest-quality frame will be activated; the rest will be added as hidden layers.  Layer names describe the size and color-depth of each frame (e.g. "32x32 (8-bpp)" means an icon frame is 32 pixels wide by 32 pixels tall, at an original color-depth of 8-bits-per-pixel, or 256 colors).

You can right-click on any layer in the right-hand Layer box, and select `Show only this layer` to view that icon frame by itself.  Similarly, the `Image > Fit canvas to active layer` command will auto-shrink the image canvas around the currently active layer, if a smaller frame is desired.  

Last night I finished up work on an "Export icon" user interface, and this weekend I will start work on the actual code that creates ICO files.  Depending on where an icon is meant to be used, many different sizes and color-depths should be embedded in the file.  It will take some work to cover all the different combinations, but I'm fortunate to already have most the code available for other file formats.  I just need to re-purpose it for ICO-specific rules.

> Did that first e-mail reply I sent arrive in the right place?

Unfortunately, I haven't seen it.  If it worked, your text would be visible in this thread.  GitHub handles all that email interaction on its own, so I'm afraid we're at its mercy.  

GitHub account privacy settings can prevent email replies from working (a good thing, actually - threads like this are publicly viewable, and replying to them by email can accidentally reveal email details you'd rather keep secret!).  I do feel bad if you lost text due to it, though 😞 

> Just wanted to let you know that I've tested the new icon importer and it works flawlessly. In fact, so does everything else in the latest nightly build.

Thank you so much for taking a look at it.  👍  I'll reply back here when exporting ICO files is ready for testing.

> Tanner, on portablefreeware.com I just discovered a tiny program that can convert PNG files to ICO, and embed several image sizes in the process.

Thank you, I'll take a look!

Best wishes for a happy weekend.

**Comment by g-busch** [comment]
No, I didn't lose any of the text from the initial e-mail, as I was able to copy and paste all of it to this thread.

Thanks for the comment on my user icon. It's actually the same one I use on my website, and was created in the Greenfish Icon Editor before I started using PhotoDemon for that purpose.

**Comment by g-busch** [comment]
Great work, Tanner, thanks! I just checked out the latest nightly build, and the export function is working flawlessly, so I no longer need an extra tool to work on icons. The only other graphics program I need now is my default viewer, XnView, but that can be practically any of the myriad viewers out there.

**Comment by tannerhelland** [comment]
With the PhotoDemon 8.0 beta release now available, I'm content to close this issue.  Windows icon (ICO) files are now a first-class citizen in PhotoDemon, with full support for reading and writing icons of any shape or size.

Thank you again to @g-busch for his help!  I'm very happy for other users to play with this new feature.
