### ISSUE TITLE
 a tool for moving more easily the pixels of the selected area

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#303]
hello , 
I try to explain: I am used to work with "paint.net" : this software has two different "move and resize"  tools 
-the first one have a blue arrow icon and you can move and resize the selected pixels of an area, 
- and with  the second one, a white arrow, you can move and resize only the selection itself.
so, this is very fast to change to change for one to another fonction.

when i work with photodemon,for example,  I load a large image, then  I  have to select an area, then go to the menu, modify> copy and again go to menu modify>paste as a layer and I can now move  or resize this area. 
as I often do photocollages, I often just move small parts of an image from a place to another place, and erase around to fit, ( without making a new layer)  and then I fill the empty zone (left by the area I moved) with the clone brush, 
so I think having an other  icon for  moving directly  the pixels of the selected area should be useful 

 otherwise, thank you for the last updates, Photodemon is better and better  !

**Comment by tannerhelland** [comment]
Hello @mizka76.  I apologize for how long it took me to add this feature, but I am happy to announce that this feature is now available in nightly builds!  Let me copy+paste the text from the pull request that merged this feature branch:

To see this new feature in action:

1) Load an image
2) Create a selection (any shape you want)
3) Switch to the Move/Size tool (shortcut: M) and click-drag any pixel within the selected area

Previously, the Move/Size tool ignored any active selection.  Now it is smart enough to notice an active selection, and it will automatically switch to "move selected pixels" mode instead of "move layer" mode.  This is how Photoshop implements this behavior, and I find it preferable to the "two separate tools" approach used by Paint.NET.  (Especially since PD's toolbox is getting kind of cramped.)

New options related to this feature are available in the "other options" dropdown on the Move/Size tool.  Specifically:
1) the tool can sample from the active layer or ALL layers (merged)
2) the default behavior of COPY or CUT (erase original pixels after moving) can be toggled.  Use the ALT key to switch between your chosen default and the alternate behavior.

I am not aware of other software that allows you to move merged image data this way (while auto-cutting relevant pixels from all affected layers), so this is a nice win for PD!

After moving the selection, you can also freely resize and rotate the pixels.

I have tested this feature aggressively and am very happy with its performance, but additional feedback is always welcome.  And of course, please notify me if you encounter any bugs!
