### ISSUE TITLE
Layer Folders

### ISSUE THREAD

**Issue by Fivavoa** [tannerhelland/PhotoDemon#305]
Hello! First of all, I want to thank you for all the hard work you've put into this project! It's amazing and phenomenal and has helped me be more efficient in a lot of ways.
To start off, I'm unsure if this should be considered a bug,or if you plan on adding it, etc etc. However, it's somewhat inconvenient when trying to work with colleagues who are using Photoshop. While I could do the task on GIMP instead, PD to me just has a better workflow and it's just snappier and nowhere near as sloppy.

Anyway, the issue in question is _when importing PSDs with folders, PD translates all layer as visible ones_.
PD doesn't have folders for layers as far as I can tell, so when a colleague has a complicated PSD, it just shows up extremely messy. Any invisible layers within folders all gets translated to visible all at once.

This is what it looks like:
![image](https://user-images.githubusercontent.com/29827600/87080109-1e6f9980-c1f5-11ea-9441-d9af0abd424e.png)

Sorry for the inconvenience, and thanks again!

### Version information
 - PhotoDemon 8.0 alpha (build 2047)
 - Windows 10 Home 1909

**Comment by tannerhelland** [comment]
Hello @Fivavoa!  This is an excellent bug report.  I am grateful you caught this.  Thank you for reporting it to me.

You are correct - PhotoDemon does not support layer groups (yet).  When loading Photoshop documents, PhotoDemon previously ignored layer group data since it had no way to utilize it.

I have patched my PSD code to now read layer group data, and make sure that layers which are part of an invisible group are now hidden by default when the PSD file is loaded.  This should produce a much "cleaner" image, and of course the hidden layers will still be available if you need to toggle them.

I have a follow-up question for you.  Some 3rd-party PSD readers, like the PSD plugin for Paint.NET, handle layer groups a little differently.  Paint.NET does not support layer groups, but when loading a PSD file, their PSD plugin creates "blank" layers with the names of layer groups attached, so that you can at least see where the groups belong.  Here is a screenshot:

![image](https://user-images.githubusercontent.com/1930029/87191313-6653f680-c2b1-11ea-87ba-2ff60b9317cf.png)

The same file loaded into GIMP (which *does* support layer groups) looks like this:

![image](https://user-images.githubusercontent.com/1930029/87191505-c77bca00-c2b1-11ea-90c2-d3f83e9958ba.png)

Would it be helpful to do something similar in PhotoDemon?  I ask because I am conflicted.  It's not hard for me to add this "feature", but it could add a lot of "junk" layers to some PSD files, which has performance and usability implications.  However, maybe those trade-offs are worth it if the "fake group layers" help users make better sense of PSD file contents, at least until PhotoDemon properly supports layer groups.

I am open to input either way.

(For your help, I am happy to add you to the program's contributor list.  Just let me know what name and/or website, if any, you would like me to use.  Thank you again!)

**Comment by Fivavoa** [comment]
I think it would depend on whether saving it again would keep the layer groups in other software (i.e. Photoshop, GIMP, etc). If the new layers made to indicate layer groups sustain the actual layer groups for software that has compatibility, I'd say _maybe?_

I've spent some time thinking about it and I'm sure just ensuring that the file identifies which layers are supposed to be visible is enough. Maybe extra layers might be too much to dig through, especially with no way to organize them beyond renaming them. I appreciate the perspective though, I didn't know Paint.NET did that!

(Also, I appreciate it! Don't worry too much about it, just keep my username if you want. I don't really have a website, I simply wanted to help software I really enjoyed!)

**Comment by tannerhelland** [comment]
I apologize that it took me a few days to reply to this!  Thank you so much for the feedback.  

In the interest of minimizing clutter, I'm *not* going to add PSD layer groups as "dummy" layers at present.  I'd rather wait and just implement layer groups correctly, because doing a half-assed job now would introduce a lot of complexity without actually improving PSD compatibility in a meaningful way.  (Plus there are ugly performance considerations with dozens upon dozens of dummy layers getting added to imported PSD files, and these go away with a "proper" layer group implementation.)

Anyway, layer groups are on my to-do list.  Hopefully it won't be too many months/years/millennia before they appear in PD.  ;)

Thanks again for your help with this!

**Comment by Fivavoa** [comment]
This doesn't necessary cause urgent issue or anything, but I found that if you save a PSD that originally had layer groups in PD (even with the fixed display issue), PD deletes the layer groups entirely, so when you open that same PSD in Photoshop or GIMP, those layer groups are gone. Unsure if this was intentional or not.

**Comment by tannerhelland** [comment]
Hi @Fivavoa.  Thank you for following-up on this.

> if you save a PSD that originally had layer groups in PD (even with the fixed display issue), PD deletes the layer groups entirely, so when you open that same PSD in Photoshop or GIMP, those layer groups are gone.

Yes, this behavior is intentional per the discussion above.  

I can't preserve layer groups without giving the user some kind of access to them.  Otherwise, the positioning of any groups becomes indeterminate after editing the file in PD.  (e.g. what if the user rearranges layers?  How do I know where to place the original PSD groups in the saved file, if layer order is now different than when the PSD was loaded?  What if the user deletes layers, or adds new ones?  There are a lot of ways to "break" the original layer groups, so the user has to have a way to work with the grouping order inside PD for groups to be safely preserved.)

Short of implementing full support for layer groups (which I can't do this close to a new release), the aforementioned Paint.NET workaround is the only alternative I know of.  Their 3rd-party PSD plugin creates blank "dummy" layers for the start and end of each layer group.  These behave like normal layers, in the sense that you can reorder them, delete them, or even add new ones provided their layer names clearly identify them as "groups".

When saving the file out to PSD, the PSD exporter looks for the "group" keyword in layer names, and sets matching flags in the saved PSD file to re-create matching Photoshop layer groups.  (And if saving to other image formats, the groups just appear as a bunch of empty layers.)

As mentioned before, this can make the layer list quite large (no way around that), with some corresponding performance complexities (possibly not a deal-breaker), but it *does* provide a mechanism for PD to preserve layer groups when loading/saving PSD files.  I can add this feature in the coming days so we can try it out and see if it works better than the current "lose grouping completely" approach.

**Comment by Fivavoa** [comment]
Perhaps a way to ask the user whether they want to preserve layer groups or not upon loading a psd with layer groups would be a good idea? That way, for those with no intention of using PS or GIMP or w/e can just have a clean list for PD exclusive usage. Or those that prefer to use PD, but need the PSD intact to distribute it to co-workers or something could be something until PD naively has layer grouping?
What do you think?

**Comment by tannerhelland** [comment]
> Perhaps a way to ask the user whether they want to preserve layer groups or not upon loading a psd with layer groups would be a good idea?

To be honest, prompts like this are a last resort for me.  They are complicated to localize, they wreak havoc during batch processing (processing gets interrupted by pop-up boxes), and they can be frightening for beginners who don't understand what's being asked (e.g. beginners who may not know what "layer groups" even are).  So while I like the idea of users being able to choose, a lot of complexities arise with trying to handle it with a prompt.

For now, I've just gone ahead and mimicked the approach that the 3rd-party Paint.NET PSD plugin uses.  In the latest nightly build, PhotoDemon now loads layer groups from PSD files as blank "dummy" layers.  This allows you to rearrange groups, delete them, or even add new ones (by using the special "Group start: " and "Group end: " prefixes in a layer's name).  

When loading a PSD with groups, editing it, then saving it back out to file, groups will now always be preserved.  I've done what I can to reduce the performance hit of working with images like this, and even though this is sort of a hackneyed approach, I of course like that groups are no longer just "lost".  I think this strikes as good balance as I can until PD itself supports layer groups.

Here's the catch: I don't own a copy of Photoshop, so I've only been able to test the new PSD code against 3rd-party photo editors.  (GIMP in particular has been very helpful, since it natively supports both layer groups *and* PSD files.)  So if you have access to Photoshop, it would be a huge help if you could run a few tests for me.  I just want to double-check that the way I'm writing layer groups to PSD files is compatible with Photoshop itself!  Thank you!

**Comment by Fivavoa** [comment]
Ah, I suppose I understand how prompts can mess with background stuff. How about simply leaving it as a settings option instead for power users in that case? You could probably place it in Tools > Options > Loading and call it something like "Open PSDs with pseudo-layer groups" or "Open PSDs with layer groups as dummy layers"

As for if it works, I tested it on Photoshop 2020 and it works perfectly! I tested renaming and making a layer group in PD build 2130, then opening the PSD in Photoshop, and it translated just fine!
Some recommendations about layers while I was testing:

Can you add an option to create two dummy layers instantly as an option in the "add layer"? That way, users won't have to manually name the layers Group start: and Group end:. Just a recommendation, maybe not worth the effort to work on this so much since it's just a temporary solution, but just a thought.

Can there be an option to reassign layers? For instance, if you accidentally make a layer fully black instead of transparent, I think it would be nice to have a right-click option to reassign the background again (something similar to what graphicsgale does in it's layer menu options, since as it stands right now PD barely even has right-click layer options to begin with)
Since otherwise users would have to delete the layer and remake it with the right background, or use a selection tool and manually reassign/delete it or something.

Just small QoL things I think would be nice, otherwise the layer folders thing works just fine. Good stuff :)

**Comment by tannerhelland** [comment]
> As for if it works, I tested it on Photoshop 2020 and it works perfectly!

Yay!  That's great news.  Thank you so much for letting me know.

> How about simply leaving it as a settings option instead for power users in that case?

With an 8.0 beta available (and an official release coming later this month), I'm afraid all text in the program is currently on lock-down.  (PhotoDemon's volunteer translators are currently working on translating all the changed text in this release, and I can't add new text now without risking my safety.  😉 )  

Post-8.0's release I could look at doing this, but honestly, I'm more inclined to spend my time just getting full layer group support added!

> Can you add an option to create two dummy layers instantly as an option in the "add layer"? That way, users won't have to manually name the layers Group start: and Group end:.

So here's my compromise on this.  I can't add new UI options as already mentioned, so what I've done is added a "secret" way to trigger the creation of two groups.  (This is super hack-y, but it's better than nothing.)

In the latest nightly build, if you attempt to add a new layer and the layer name starts with "Group start:" or "Group end:", PhotoDemon will automatically detect those keywords and create two layers instead of one (and the layers will be properly named).  

So for example, if you click "Add new layer" at the bottom of the layer panel, and enter the name "Group start: Group 1", PhotoDemon will now auto-recognize the "Group start:" prefix and quietly add two layers to the image - one named "Group start: Group 1", and another named "Group end: Group 1".

I don't like resorting to silly workarounds like this, but this close to a new stable release, my options are limited.  (Again, proper layer group support will make these workarounds pointless... but in the meantime, I hope this helps.)

> Can there be an option to reassign layer backgrounds?

The fastest workaround (for now) is to use the paint bucket tool to just fill the newly created layer with whatever color you want.  

To convert a color layer to a blank (transparent) layer, change the paint bucket's blend mode to "erase" (at the bottom of the blend mode list), then click anywhere on the layer to "fill" it with 100% transparency.

> PD barely even has right-click layer options

It's true - good right-click context menus could simplify complex layer interactions!  PhotoDemon's layer features have traditionally hewed closer to lightweight editors like Paint.NET (which similarly avoids right-click menus throughout its main interface, in part because touchscreens make it problematic to lean too much on context menus).  

But as time has passed, PD's layer toolset has gotten increasingly complex, and with this new 8.0 release (finally) offering interoperability with Photoshop files, the next release could be a great time to add detailed right-click context menus throughout the project.  I'll see what I can do after 8.0 releases.  👍

**Comment by tannerhelland** [comment]
Thank you again for all your feedback on this issue, @Fivavoa.  All the changes referenced above are available in PD's recent 8.0 release, and I think they provide an excellent "holdover" until PD gains full support for layer groups.

I'll close this issue for now, but if you encounter any other oddities when working with PSD files, please let me know.
