### ISSUE TITLE
[BUG] - Disappearing dialogue box when right-click closing while minimized

### ISSUE THREAD

**Issue by Fivavoa** [tannerhelland/PhotoDemon#307]
### Version information
 - PhotoDemon 8.0 beta (build 2102)
 - Windows 10 2004

### Describe the bug
Usually when you're focused on another window, when you try to close PD with an image you edited but haven't saved using the right-click menu, PD would automatically switch back and add a confirmation box to ask if you would like to save/close/etc before closing. However, if PD is minimized, PD does nothing, but when you open it back up, PD cannot be interacted with. It makes the windows "attention/error" noise indicating something else requires your attention before you can interact with the GUI underneath it.
The problem is that the dialogue box never shows up again, rendering the entire PD window unable to be interacted with, requiring a force-close.

### How to reproduce the bug
   1. Have PD open with something edited and unsaved
   2. Minimize PD
   3. Attempt to close it via right-clicking from the taskbar
   4. PD should be rendered incapable of actions

### Expected behavior
PD should open back up or switch to itself automatically, bringing up a confirmation box that asks if you want to save/close without saving/cancel

### Debug logs
[DebugReport_7.log](https://github.com/tannerhelland/PhotoDemon/files/5011429/DebugReport_7.log)

**Comment by tannerhelland** [comment]
Great catch, @Fivavoa.  Thank you for reporting it!

Quick explanation: PhotoDemon uses a central manager for raising all dialogs.  This manager is responsible for applying visual styles to the window and determining its initial position (usually centered over the main PD window).

I thought it impossible for PD to raise a dialog while being minimized, but you discovered an exception to this (and I'm so glad you did).

This edge-case with the "unsaved changes" dialog creates a weird bug where the dialog manager attempts to center the dialog over the main window (whose size and position is calculated as all-zeroes), resulting in a 0x0 dialog being created at position [0, 0].  The main window locks as it goes into a modal dialog loop, and because the newly raised dialog is inaccessible, the program is effectively frozen.  D'oh!

Easy, universal fix is to simply check main window state before raising *any* dialog, and forcibly restore it to normal state before raising a modal dialog.
