### ISSUE TITLE
[BUG] - (Selection Tools)

### ISSUE THREAD

**Issue by dusko23** [tannerhelland/PhotoDemon#308]
### Version 
-  PhotoDemon 8.0 Beta (build 2102)
 - Windows 10

### The BUG
Selection Tools RECTANGLE and OVAL should select Interior of Area. Currently they select Exterior Area.
Select INVERT just changes Dimmed Area a bit. 

### Correct Behaviour
LASSO and POLYGON perform Selection OK. Select INVERT works fine it this case.

### Suggestion
POLYGON  should close POLYGON with double mouse click as well. Designated Key Press would be fine as well.

**Comment by tannerhelland** [comment]
Hello @dusko23.  Thank you for filing this bug report.

I've tried to reproduce this bug in the latest beta, but I cannot.  I think you may have changed the "area" setting by mistake.

![image](https://user-images.githubusercontent.com/1930029/89787069-21062d00-dada-11ea-9e1b-9a4a04775c99.png)

Check the circled box.  There are choices for making the selection cover the "interior", "exterior", or "border" of the selected region.  Make sure "interior" is selected (if that's what you desire).

You can also change the "appearance" setting to a different option if it is unclear which area is being selected.  

Does this solve your problem?

**Comment by dusko23** [comment]
Hi  Tannerhelland,
Indeed it was exterior when I ran the program.  I have now changed the
interior and all is working as expected.
I remember that I was playing with some settings AFTER the selection tool
did not perform as expected.
Anyway I managed to bring PhotoDemon to the state where RECTANGLE and
CIRCLE did perform EXTERIOR selection  but POLYGON and LASSO tool did
perform INTERIOR selection.
In that particular state when RECTANGLE was selected SELECT INVERT did not
perform at all.
I am aware that you are highly influenced by the use of the software and
you are clicking the same options again and again.
I on the contrary was clicking selections, not exactly knowing what will
happen and I managed to bring the software to a weird state.
No problem if you would consider my observations not relevant enough to
digg dipper. That's OK.
I would suggest that you install the same version (Beta 2102) on a computer
where software was not installed yet and give it a try.
I firmly believe that I was not changing combo box AREA  in the first
place.
By the same token I am aware that sorting out this type of errors can be
difficult.
This brings back a memory  of how Steve Jobs did test his programs.  It was
his grandma who was asked to perform a hectic pressing of keyboard keys.
If the program survives, the final test is passed :-)
My congratulations to your excellent program again.
Best regards








<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tannerhelland** [comment]
Thank you for your reply!  I'm glad we sorted this out.  PhotoDemon has a *lot* of options on various tools, and it can be a little overwhelming to keep them all straight.  (Even for me 😄 )

Re: your original post...

> POLYGON should close POLYGON with double mouse click as well.

I've just added this to the latest nightly build.  While creating a polygon selection, you can now double-click to complete the polygon.  Thank you for suggesting this - I didn't realize this is how many other editors behave!

> I managed to bring PhotoDemon to the state where RECTANGLE and
CIRCLE did perform EXTERIOR selection  but POLYGON and LASSO tool did
perform INTERIOR selection.

This is intentional behavior, actually.  Each selection tool remembers its own set of properties.  You can set separate properties for e.g. Polygon vs Rectangle selections, and PhotoDemon will remember them both.

> In that particular state when RECTANGLE was selected SELECT INVERT did not
perform at all.

Yes, this is definitely a bug!  I have tracked down the cause and (hopefully) remedied it.  Thank you for notifying me.

Thank you again for catching some bugs for me, and suggesting a good usability improvement with double-clicking polygon selections!

**Comment by dusko23** [comment]
Hi, glad to hear that many comments were of some help.
Just a note.
Some drawing programs use the escape key to undo in steps. Probably it is a
good idea to use that as well. Reason is simple. Total UNDO by pressing
escape is not needed because users do not draw that much point anyhow and
undoing in steps gives more control over the drawing scenario. Holding the
esc key until drawing session is reverted (draw polygon for example) gives
a good feeling of control. By the same token rubberbanding the last point
drawn and cursor position would be very nice to have ;-)
Again, by the same token, pressing the space bar to finish the drawing
session would be equally nice. Sometimes people have problems with
doubleclick.
Regards

**Comment by dusko23** [comment]
Hi, just found an annoying bug.
It happens when PhotoDemon runs.
Slides does not slide  using mouse move.
[image: image.png]

How to replicate a bug.

Run PhotoDemon and load a picture.
Go to either of the sliders, mouse down in the circle and tnen mouse move.
The Slider does not move, just a tiny blue spot does. When you release the
mouse button nothing happens.
After all next attempts everything works fine.
Regards

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tannerhelland** [comment]
Hi @dusko23.  Some updates on your questions and reported issues...

> Some drawing programs use the escape key to undo in steps. Probably it is a
good idea to use that as well. 

You can use the BACKSPACE key to do this in PhotoDemon.  Backspace will remove the last polygon point added (similar for lasso selections).

I prefer this key behavior as it matches Photoshop, and it also allows the ESCAPE key to behave identically across all selections (e.g. ESCAPE always cancels the active selection, instead of doing different things on polygon vs other selections).

> Again, by the same token, pressing the space bar to finish the drawing
session would be equally nice.

Great suggestion!  I have added support for using the ENTER key to finish the current polygon selection.  (ENTER was chosen to match [Photoshop's behavior](https://helpx.adobe.com/photoshop/using/selecting-lasso-tools.html).)

> Hi, just found an annoying bug.  It happens when PhotoDemon runs.  Slides does not slide  using mouse move.  After all next attempts everything works fine.

Your image did not come through (GitHub doesn't attach images sent by email), but I think I understand what you are saying.  I believe I have remedied this in the latest nightly build.

You can always grab a new development copy of PhotoDemon from [the Download page at photodemon.org](https://photodemon.org/download/) - Nightly section - or by going to Tools > Options > Updates in your current copy of PhotoDemon, and making sure the "stable, beta, and developer releases" track is selected.  Then the program will automatically download updates for you.

Thank you for all your feedback!  I am happy to add you to the contributor list for this release.  Just let me know what name and/or URL you would like me to use.

👋

**Comment by dusko23** [comment]
Hi,
I have downloaded the latest night build and indeed all bugs spotted are
sorted out.
Did play with the existing version and I have a couple of (I believe)
useful suggestions.
 1. Closing polygon with ENTER is fine. However, adding a Space bar as well
would be very nice. The thing is that the Space bar can be easily
accessed even with closed eyes and feels more natural because the mouse is
typically in the right hand while the Space bar is much more left oriented
than ENTER. It is good practice to have left left and right right :-)

2. Drawing polygon needs rubberbanding from the last point drawn to the
mouse cursor.

3. While drawing polygon double click SHOULD NOT create another point. Just
close the polygon.

4. While drawing polygons in HIGH ZOOM it is acquard to move image using
sliders. Just use the right mouse button to move the image (with polygon).
Left mouse already moves the polygon only. It is good practice to use the
right mouse to move the image. If none of the drawing tools are pending,
the left and right mouse button can move the image.

I hope that makes sense.
Regards,
Dusan

**Comment by tannerhelland** [comment]
Hi @dusko23 .  Thank you for your continued feedback!

>  1. Closing polygon with ENTER is fine. However, adding a Space bar as well
would be very nice. 

I have now added SPACE to behave the same way as ENTER.  Thank you for encouraging me to revisit this.

> 2. Drawing polygon needs rubberbanding from the last point drawn to the
mouse cursor.

This is now available in nightly builds!

> 3. While drawing polygon double click SHOULD NOT create another point. Just
close the polygon.

This has been updated in the latest nightly builds!  (I notice that other software goes both ways - for example, GIMP adds another point at the double-click location, but I agree with you, that it is best to make the double-click *just* close the selection.)

> 4. While drawing polygons in HIGH ZOOM it is acquard to move image using
sliders. Just use the right mouse button to move the image (with polygon).

I'm afraid that I disagree on this point.  I need to reserve right-click behavior for future tool capabilities, so I can't map it to canvas movement without many future repercussions.

At present, the mousewheel can be used to navigate the canvas while other tools are active.  Ctrl+scroll and Shift+scroll can be used for zoom and horizontal pan, along with normal scroll for vertical pan.  It takes some practice, but this mousewheel behavior is consistent across many different programs (photo editors, word processors, etc) so I am inclined to keep it.

I also believe that Photoshop supports use of the SPACE bar (press and hold) to activate the hand tool while other tools are active.  This could be one avenue for a future enhancement to PhotoDemon.  I will add it to my "investigation list".

**Comment by dusko23** [comment]
Hi Tanner,
I appreciate your concerns about consuming precious mouse events and
reserving them for future use,
Did play with the last build and building polygons having rubbernading to
cursor feels excellent.
I tried Lasso tool as well and I suggest that you mark the mouse down point
with a BLUE DOT (similar to Polygon first point) because it is difficult to
find it  when the image is packed with details. Like topographic maps are.
Regards

**Comment by tannerhelland** [comment]
Thank you again for all of your feedback on this issue, @dusko23.  All of the changes referenced above are available in PhotoDemon's recent 8.0 release.

Before the next stable release, I hope to migrate PhotoDemon to a new selection engine that supports multiple selections (among other improvements).  I have this issue bookmarked to help me remember not to break any of these existing features in the process 😉

**Comment by dusko23** [comment]
Hi Tanner,
I am glad that I can be of some help.
Multiple selection is a great concept.
I have played with version 8 and it looks very nice.

Considering the new selection engine I would advise to omit
exterior/interior.
By default, the interior is always selected and can be inverted by
Select/Invert. Simple and efficient.

Coloring selection does not really serve the purpose because it does not
change the image as such. Why "change" the image then? Why
emphasize something when the user knows exactly what he is doing -
selecting the interior?
Lightbox can be simplified by just painting the exterior differently. Just
make the exterior lighter. That is all that is actually needed. Users just
want to see the mild difference between selected/non selected. And you will
get rid of extra settings. Remembering all these settings for every
selection tool means a lot of programming and testing (I have found a bug
here by playing with settings but would need to play again and remember
what I am doing to tell you). Might create video though.
I believe that my suggestions can make your life easier when implementing
multiple selection.
The sole purpose of the selection tool is to select something ☺.
Resizing the text box to the actual text boundary when typing/changing text
would be very nice.

Regards,
Dusan



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tannerhelland** [comment]
Hi @Dusan.  I apologize that it has taken me so long to reply!

> Considering the new selection engine I would advise to omit exterior/interior. By default, the interior is always selected and can be inverted by Select/Invert. Simple and efficient.

Select > Invert (and Select > Border) have a huge limitation in all software, even Photoshop.  

Using this option forcibly converts the selection from a vector object to a raster object.  This means you can no longer freely resize the selected area, because it is no longer defined as a vector shape.

PhotoDemon's selections don't suffer this limitation, because you can freely switch between interior, exterior, and border modes **while the selection remains in vector mode**.  This allows for very fine positioning of e.g. a border selection, which is otherwise impossible in Photoshop.

This capability is integral to PhotoDemon's selection tools, and was a key reason for me adding selection tools in the first place - to fill a feature gap in other editors.

As for the "display" modes of selections, these were not originally present.  PhotoDemon originally defaulted to "lightbox" mode because that's what I prefer for e.g. crop operations (same as Photoshop).  But users complained because some wanted Paint.NET's default behavior ("highlight" mode).  Other users wanted an outline mode, while still others wanted an animated "marching ant" mode because that's what they were accustomed to.

Because PhotoDemon's selection engine is built atop vector shapes, it's surprisingly little work to enable these various modes.  (Basically just switching between stroking or filling the current shape, with some workarounds for non-vector modes like the magic wand.)  Highlight and lightbox modes will also be critical in the future when implementing a "selection brush", which is necessary for a full-featured layer mask implementation, so it's not as simple as only providing one or the other - they both have merits depending on the task at hand.

So that's some of the reasoning and implementation details for why PhotoDemon's selection tools work the way they do.  How they appear today is the result of many years of iterations (and feedback!) from many different types of users, and these are the kind of details I have to weigh when modifying the way they behave or the features they support.

> I have found a bug here by playing with settings but would need to play again and remember what I am doing to tell you.

Please let me know if you can re-create the problem!  Thank you in advance 🙏

**Comment by dusko23** [comment]
Hi Tanner,
thank you for the elaborate answer regarding selection tools.
I appreciate that selection tools were developed over a period of time and
reflect the needs of different users' initiatives.
Some users like Photoshop, some Paint.NET, some Gimp or any other drawing
software. That is just fine.
And you served them all which is great.
If I may, I suggest that you add just a simple but effective trick to
PhotoDemon software where the user from the tool bar menu selects which
family of selection tools he wants to use.
Like: Photoshop, Paint.NET, Gimp or All Selection Tools. If I may I suggest
that by default Photoshop selection tool is set by Default
because PhotoDemon is in a sort of reflection of PhotoShop.
That would give an extra professional flavor to PhotoDemon ("we have them
all, just pick your choice"). Having them all available in the first run
might confuse the user (like me, former fan of Photoshop, later struggling
with Paint.NET, Gimp and currently implementing some cute postcards for
kids using PhotoDemon like a breeze ;-)
Users which are familiar and have used all selection tools  before
switching to PhotoDemon are very rare.
As far as selection vectors are concerned I see any selection tool as
vector(s). To me, Invert selection is a vector as well but with a hole in
inverted polygon.
Just to wrap up a selection tool. I will create a video of a tool which can
easily be used as another selection tool. A tool which I haven't seen
anywhere before so I created it to make complicated selection a breeze. And
would not mind if you would implement it at some point as well. From a
human perspective, selection is something we are doing on a daily basis
hundreds of times a day. And the logic of mind wants many choices available
but properly presented to make a selection process straightforward.

Will try to replicate the selection bug by video grabbing.

Regards,
Dusan
