### ISSUE TITLE
source tools, clipboard image,  updated french translation 

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#309]
### Hello ! 
- keeping the chosen options of the user for "source tools" when opening photodemon again after closing it , should be helpfull : every time I open photodemon, these options are always "on" , and I have to uncheck each time " automatic activation of layers under the mouse cursor" that I do not often use.

- After a copy /paste , the clipboard image naming in the layers is followed automatically by the date , why not an incremented number instead of the date ? 

- a keyboard hotkey for "Cut from layer " should be fine too, as I often use it .

- and a little bug I just found : I wanted to make a screen capture ( with the last nightly version)  , and I used the keyboard key "print screen" and then in photodemon "import>clipboard image : and when i wanted to "save" or "save as" this image :  no window opens for doing  this opération...... ( same thing when I click on the cross or by the menus, or in the image rubbon, impossible to have the window for naming  the file or choosing  its format) Photodemon do not crash, and closes the image only if I click on "dont save changes" .
but, if I make the screen capture with photodemon ,  it is ok , I can "save", or "save as", a window appears for naming and saving the file . 

  here the updated French translation for the new apng screen capture options and ico added.
[French.zip](https://github.com/tannerhelland/PhotoDemon/files/5065857/French.zip)

a great "Bravo" again for all your work !
...

**Comment by mizka76** [comment]
ouups ! it is a big mistake of mine !  (  the translation of "clipboard image" is wrong : it should be "image du presse papiers" (i tried to make a différent version of the traduction for me, for teaching , less "pro" and more explicit for my pupils, who better understand that it is an image issued from a "copy and paste" and my mistake was to write it with a slash ( tranlated as "copié/collé" instead of "copier-collé" that make impossible to save the file ! and i forget to change it) 
very very sorry ! 
the corrected translation 
[French.zip](https://github.com/tannerhelland/PhotoDemon/files/5069950/French.zip)

**Comment by tannerhelland** [comment]
Hello @mizka76!  Thank you very much for the updated French translation and the great list of suggestions.  I think I have added all of them successfully.

> keeping the chosen options of the user for "source tools" when opening photodemon again after closing it , should be helpfull : every time I open photodemon, these options are always "on" , and I have to uncheck each time " automatic activation of layers under the mouse cursor" that I do not often use.

I have updated the `Move/Size tool` so that it now remembers settings between sessions.  I didn't realize it was not doing this - thank you for notifying me!

> After a copy /paste , the clipboard image naming in the layers is followed automatically by the date , why not an incremented number instead of the date ?

This is a great suggestion, thank you!  Pasted layers now use an incremental number appended to their name, instead of the current date.

> a keyboard hotkey for "Cut from layer " should be fine too, as I often use it .

This one is a little harder, as the relevant shortcut would be `Ctrl+Shift+X`... but that shortcut is mapped to `Crop to selection`, to match Photoshop behavior.

An "ideal" solution would be a way for users to modify shortcuts themselves.  I hope to add this in the future, but it is not available right now (short of editing the source code yourself, of course).

So what I have done is instead add two new hotkeys to match options from Photoshop's `Layer > New` menu:

`Ctrl + J` -> Add new layer via COPY
`Ctrl + Shift + J` -> Add new layer via CUT

These new shortcuts are active in the latest nightly build, but they are **not** available in PhotoDemon's `Layer > Add` menu.  I can't add new text to the program this close to a stable release because all localization files would need to be re-distributed to translators.  So instead, I will add the shortcuts now, and as soon as 8.0 is released (later this month), I will start work on a new 9.0 build that includes matching menus in PhotoDemon's `Layer > Add` menu.

I hope this helps!  As an extra convenience, when you use these shortcuts, they automatically position the new layer at the mouse cursor position, if the mouse is over the image.  This makes it very fast to position the new layer where you want it, I hope.  (The `Edit > Paste as new layer` menu also does this, when `Ctrl + Shift + V` is used).
