### ISSUE TITLE
Possible layer list changes for improved UX

### ISSUE THREAD

**Issue by jpbro** [tannerhelland/PhotoDemon#311]
Hi Tanner,

As mentioned in our email correspondence, absolutely no rush on the issues/requests I report here.

This issue concerns the layer list in PD, and there's 4 things that I think could be changed for a better experience:

- When the scrollbar of the list has focus, the up/down arrow keys move the list 1px at a time, making scrolling long lists slow. I think it would be better if the arrow keys scrolled up/down the height of one full list item (without changing the selected list item).

- When the list itself has focus, the arrow keys change the selected item as expected, but when the selected item is outside the view port, the view port doesn't scroll to show it. Once you leave the view port, it's impossible to tell which layer is selected. I think it would be better if the view port scrolled to show the focused item.

- When dragging a layer to a new position in the list, the list doesn't scroll when you reach the top/bottom, making it a bit painful to move layers around in long lists. It would be ideal if the list would auto-scroll while you drag a layer.

- When dragging a layer to a new position, some extra visual feedback that you are in a drag operation might be nice (like a red line at the threshold between the selected layer and the new position. This request is a bit questionable, I just found that it was hard to tell at glance whether I was actually dragging (when the layers all had similar names and appearances after recording an APNG), or if I was changing the selection highlight to new list items. Maybe even just changing the highlight colour when dragging would do the trick?

Thanks for considering the above requests, and all the best!

**Comment by tannerhelland** [comment]
Okay, all these items were (barely) implemented before 8.0's release, and testing in the ~10-ish days since leaves me relatively confident that nothing critical broke in the process!  😄 

- Layer list scrollbar now scrolls up/down in much larger increments
- When the active layer is changed (via any mechanism, including arrow keys when the layer list has focus), the currently selected layer is always made visible in the list, auto-scrolling as necessary.
- Dragging layers into a new position now auto-scrolls the list as long as the cursor is near-or-outside list boundaries (on top or bottom)
- When a layer is actively being dragged, it is now drawn indented relative to "normal" layers.

Thank you for filing this excellent issue, @jpbro.  🙏 If any of the changes don't look right, or if you notice other UI papercuts, please let me know!
