### ISSUE TITLE
APNG & Animated Layer Enhancements

### ISSUE THREAD

**Issue by jpbro** [tannerhelland/PhotoDemon#318]
First off - holy smokes is the new APNG screen recording feature great! Many, many thanks for developing this feature! 

Second, since I hate to let any good deed go unpunished, I have a few requests for enhancements ;)

- It would be nice to see the total time of the animation somewhere (perhaps on the preview pane)? Sometimes I'm trying to ensure I'm within a certain time.

- When dragging the animation preview progress bar, it would be nice if it also selected the frame in the layer list (and showed that layer in the main window). This might be too slow though? Maybe if it selected the current frame only when you release the mouse?

- After recording and saving an APNG, it would be nice if it opened in PD. Or if users don't generally want this to happen, then maybe it could be an option? So far in 100% of cases I've wanted to work on the frames immediately, and I have to go throught File > Open > Locate & Select file to do so. 

- When looking through frames/layers, we have to toggle visibility on layers on/off. For most images this is the desired behaviour because your layers are typically composited to form a single final image. With animations though, it's not a composite single image but a series of separate images forming an animation sequence. It would be great if there were some way to make one layer visible and all other layers invisible - perhaps Ctrl+Click the eyeball/visibility icon in the layer list would be appropriate?

Once again, kudos on this killer feature!

**Comment by tannerhelland** [comment]
Hello @jpbro!  Thank you so much for your feedback over the past few days.  Detailed comments like yours take a ton of effort to write, and they provide an incalculable amount of help.  🙏  I am in your debt.

I apologize in advance because my responses will be sporadic.  I'm still sorting through what I can solve before 8.0 releases and what will need to wait a bit longer, and sometimes I need a few days of trial-and-error to figure out which direction to go.

I just wanted to quick let you know re: the last bullet point above...

> It would be great if there were some way to make one layer visible and all other layers invisible - perhaps Ctrl+Click the eyeball/visibility icon in the layer list would be appropriate?

Right-click any layer in the layer box to see a (single-item) pop-up menu with this exact option.  That single-item popup menu maps to an identical trigger in the (more cumbersome) Layer > Visibility menu.

There's a longer story to explain why the layer popup menu is so sad, and why this is the only item on it... but I won't bore anyone with it here. 😆 

I very much like your idea of Ctrl+clicking the visibility icon to achieve the same thing.  A quick bit of searching shows that GIMP uses Shift+Click for this, while Photoshop uses Alt+Click.  (And a second alt+click on the visibility icon makes *all* layers visible once again - neat!)

I'll survey a few other apps to see if there's wider consensus on which key modifier to use and how exactly it should behave.  Thanks so much for pointing me in this direction, and hopefully I can have results on other items soon too.

**Comment by tannerhelland** [comment]
Okay, I think this issue is pretty much wrapped up!  Here is the current state of the items mentioned in the OP:

> It would be nice to see the total time of the animation somewhere (perhaps on the preview pane)? 

Total frame time is now available via tooltip on the Overview scroll bar (for scrubbing through the animation).  Please let me know if this isn't enough and I can look at an alternate placement.

> When dragging the animation preview progress bar, it would be nice if it also selected the frame in the layer list (and showed that layer in the main window). 

After scrubbing through the animation preview, PD will now automatically set the active layer to match the selected animation frame.

> After recording and saving an APNG, it would be nice if it opened in PD. 

There is now a toggle for this behavior in the pre-recording settings screen.  Also, if the user chooses to export an animation directly to file, that file will still appear in the Open > Recent Images list for easy retrieval.

> It would be great if there were some way to make one layer visible and all other layers invisible - perhaps Ctrl+Click the eyeball/visibility icon in the layer list would be appropriate?

Because different apps use different modifiers for this, PD will recognize any of Ctrl+Click, Alt+Click, or Shift+Click on a layer's "eyeball" icon as a request to make *just* that layer visible.  (And like other software, Ctrl+Clicking a *second* time will make *all* layers visible.)

Thank you so much for these suggestions, @jpbro!  🙏   I think their combined effect(s) result in a much-improved APNG recording experience.  Also, if any of the implementations don't behave quite how you envisioned, please let me know and we can find a better way to do it.

(Now to record all the animations I need for PhotoDemon's help files... 🤯 )
