### ISSUE TITLE
rotated and resized image , copy /paste=wrong size & orientation

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#324]
### wrong image size and orientation in a rectangular or elliptic selection ( after riotation and resizing an image or layer)
-  I opened an image, rotate it upside down, change its size to smaller and then copy, then paste, and what I got inside the pasted selection is not at the good size and not inverted as i did when I rotate the image ( it is like PD has copied the original image)

sorry, i dont have much time today ( I'm back to school now) , i will try again this week end and send a debug file ( if you have not yet solved this easily as always ! )

I updated the french translation , but "paste as new image" is not translated in the menu ( "coller comme nouvelle image " does not appear ( it was  at the line original>"&paste". therefore) ... and "preview disabled" ( aperçus désactivés) in the new animation options (when "no" is selected)  is not translated too.

- about the menu "modify"  , I made "cut", "copy" "paste" in upper case in french version so it should be found more easily  through the different variants. ( maybe useful also for other langages , because in US or english you need just two words but in a foreign langage  its sometimes more difficult  to do so  )

- in the new animation menu for "animation enabled for his image"  I added "needs two layers or more" in french , as information for  the newbies who will discover how to do a gif. ;   a little explanation under "the frame time" cursor  should be helpfull too to explain that  "the interval will be added to the end of the  layer name" 
[French.zip](https://github.com/tannerhelland/PhotoDemon/files/5165479/French.zip)
 .

**Comment by tannerhelland** [comment]
Thank you so much for reporting this bug, @mizka76!  I am horrified at the problems that manage to escape my notice 😱 

I have also fixed the missing translations you caught.  Thank you for finding them.

> about the menu "modify" , I made "cut", "copy" "paste" in upper case in french version so it should be found more easily through the different variants.

I will leave this to your best judgment.  In the case of English, I often check a few other software programs (Google Image Search is useful for this - e.g. I will search "Photoshop Edit Menu", "GIMP Edit Menu", etc) to see what they do.  

In English, PhotoDemon menus adhere to two strict rules per [Windows design guidelines](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/bb246448(v=vs.85)):

1. "Sentence case" behavior - specifically, the first letter of each menu item is capitalized, and subsequent words are *not* capitalized.  (This is likely an English-specific quirk?)
2. Ellipsis "..." are used on any menu item that raises a dialog box (instead of performing an action immediately)

I have no idea if these guidelines extend to other languages.  I will defer to your français expertise - whatever you decide is good for me!
