### ISSUE TITLE
[BUG] - Image > Trim Empty Borders keyboard shortcut not working

### ISSUE THREAD

**Issue by diego10arg** [tannerhelland/PhotoDemon#329]
### Version information
 - PhotoDemon 8.2
 - Windows 7

### Describe the bug
When I press Control + Alt + X (keyboard shortcut to trim empty borders) PhotoDemon will not cut the image but show a message: Unknown processor request submited: trim empty borders.

If I go to the Image menu > trim empty borders it works properly.

### How to reproduce the bug
The more detailed, the better!  If at all possible, a list works best, e.g.:
   1. Open image
   2. Press Control + Alt + X

### Expected behavior
It should trim the image.

### Thank you!
Thanks :D

**Comment by tannerhelland** [comment]
Thank you so much for catching and reporting, @diego10arg!  This is an embarrassing bug 😨 

When I added an option to trim empty borders from layers (as well as the entire image), I didn't remap the hotkey to match.  It should have been mapped to "Trim empty *image* borders" instead of "Trim empty borders".  Yikes, that was a bad one.

I'm just now uploading a nightly build with the fix.  Thank you again 🙏
