### ISSUE TITLE
[BUG] - Batch Operations "set export settings for this format..." crash

### ISSUE THREAD

**Issue by Fivavoa** [tannerhelland/PhotoDemon#330]
Hello again, I would like to congratulate you on 8.0's release! Fantastic work like always. Anyways;

### Version information
 - PhotoDemon 9.0 pre-alpha (build 16)
 - Windows 8.1

### Describe the bug
I'm trying to convert webp images into PNGs without editing operations. When I get to the point where it says "set export settings for this format..." it crashes when I click on this option.
**_This only happens with GIF and PNG image formats_**

### How to reproduce the bug
   1. Go to Batch Operations > Process
   2. No photo editing actions, next
   3. Add all images (in my case, it's 19 webp images)
   4. Click on "set export settings for this format...", then it proceeds to crash 

### Expected behavior
Probably a window allowing for image options similar to this I'd imagine:
![image](https://user-images.githubusercontent.com/29827600/93248080-577c3b00-f75d-11ea-972e-9a95b1a4c75d.png)

### Debug logs
[DebugReport_7.log](https://github.com/tannerhelland/PhotoDemon/files/5226889/DebugReport_7.log)

**Comment by mizka76** [comment]
hello ! 
yes I found this bug too ( Photodemon 8, 9beta 16 on  windows10) . 
I tried also to convert first a list of Webp images in PDI format > it was OK, then to PNG format : Photodemon freezes , only the first png file of the list was created.  The second time I tried , ( converting the PDI files created before, to PNG) it crashes before opening the panel shown by Fivaoa.

.... if it can help : as I wonder if it was a problem with the webp format of my images ( all of them were downloaded on Internet, some with or without transparency) , I tried on another software : 
On my ten Webp  images, three of them were described as "invalid" when I tried to open them in Paint.Net ( with the last updates), but : PD  opens all the files with no problem (Yessss!) 
so, I have opened  the "bad" webp images with Photodemon and then saved them one by one in the same webp format ... and after that Paint.Net was able to open the files .    =  PD is yet better on opening and saving this format.

**Comment by tannerhelland** [comment]
Thank you for the bug report, @Fivavoa !  (And thank you for the follow-up, @mizka76 !)  I apologize for this bug.

Your hint that it only happened with GIF and PNG images was an excellent clue.  It led me straight to the cause.

I recently added code to automatically switch between animated and static GIF/PNG export pages - depending on the state of the current image.  This was done to make the Save button more intuitive - if the current image is animated, "Save as GIF" would e.g. bring up the Export Animated GIF page instead of the normal Save GIF page.

But before a batch process begins, there is no active image, so when PhotoDemon scans the active image to see if it is animated or not, it crashes.  It was a silly mistake on my part to forget about this series of events.

The latest nightly builds have resolved the issue.  Thank you again!
