### ISSUE TITLE
[Feature request] - It's time for collapsible panels [PhotoDemon 9.0]

### ISSUE THREAD

**Issue by Kroc** [tannerhelland/PhotoDemon#333]
Do you have a roadmap planned for PhotoDemon 9?

On my little screen, things are getting way too cramped in PhotoDemon's default layout:

![image](https://user-images.githubusercontent.com/142650/93937559-e7068880-fd1f-11ea-9727-51e7a4cdc6cc.png)

Compare with, for example PSP7:

![image](https://user-images.githubusercontent.com/142650/93937253-56c84380-fd1f-11ea-9229-0037afcebe57.png)

The left & right panels are not so much a problem, but it's the bottom panel that really irks me; vertical screen height is already limited on a widescreen and the tools panel gives me this feeling like I'm trying to peek over a wall I'm too short for :P

The fact that it aligns to the left, off the edge of the document window is strangely uncomfortable, like something is just *wrong* with the way things are lined up, even though it makes perfect sense. If the tools panel were at the top of the window, at least it would be situated near the 'top-heavy' toolstrip and look more like a 'ribbon' interface.

There's no escaping the fact that tool-options need to be horizontal. I would never recommend putting that stuff in vertical panel. Every piece of software that's done that has failed, e.g. Word, LibreOffice.

**Comment by Kroc** [comment]
Some off-the-cuff suggestions:

* Put the tool options panel at the top of the window _between_ the left & right panels; move the image-strip to the bottom of the window (yes!), where it can better use the width of the screen

* Make the tool panel auto-hide, as an option

* Go full ribbon. Each tool is effectively a ribbon-tab with its tool options in it. Strong associativity with tool<->options, rather than having two disconnected panels that magically affect each other

**Comment by Kroc** [comment]
**Rough** mockup:

![image](https://user-images.githubusercontent.com/142650/93944049-c2181280-fd2b-11ea-944a-da3c4e2a3452.png)

**Comment by Kroc** [comment]
Another, more playful, mockup that shows a pseudo toolstrip-ribbon:

![image](https://user-images.githubusercontent.com/142650/93946514-618bd400-fd31-11ea-858a-79b1f61d83df.png)

**Comment by mizka76** [comment]
Yes ! I agree with all this ! ( PsP 7 was a so good basic software with this so useful tool ribon that I used it over twenty years !)

- adding two more icons at the bottom of the layer pannels would be fine ( like in the Paint.Net interface : one for merging down a layer, and another one for duplicating a layer ). the fact that in PD   the opacity of the layer is on the right pannel is a great advantage (I never liked the Photofiltre or paint .net  box that you must open for this option so oftently used) .

-

**Comment by tannerhelland** [comment]
Thank you for the feedback and mockups, @Kroc!  You're right - I am certainly past-due for revisiting this.  PD's current tool options layout came about when PD didn't have any on-canvas tools, and its design has aged... let's say "very poorly".  😆 

Note that the image tabstrip can already be placed on any canvas edge (even vertically).  Use the `Window > Image tabstrip` menu to change its location.

The biggest difficulty in shrinking the width and height of the tool options panel (especially while supporting 1024x768) is that I haven't written all the UI elements I need to make it work.  My primary need is a flyout container panel, where I can place any number of child options for complex tools.

Multi-purpose flyout panels would greatly improve a lot of UI pain points in PD, but they are tedious and difficult to implement, especially given the need to support both XP and Win 10.  I keep putting them off because unlike many tasks, this is one where I know what I'm getting into and I dread it.  

Any number of features are waiting on this - for example brush shapes other than "circle" need a custom flyout panel to preview and switch between them, but because I don't have one, I simply don't expose that tool feature yet.  

I'll try to remember to tag this issue as I (very slowly) muddle toward a better solution.  Ongoing feedback is always welcome.

@mizka76: 

> "adding two more icons at the bottom of the layer panels would be fine ( like in the Paint.Net interface : one for merging down a layer, and another one for duplicating a layer )"

These are now available in nightly builds!  Thank you for the suggestion.  (As the button tooltips suggest, shift+click the "move-down" button to perform a merge-down instead.)

**Comment by tannerhelland** [comment]
It's been a long time coming, but I've finally (mostly) finished a framework for PhotoDemon's new toolbox design.  Here's a short animation of testing tab key navigation on the Move/Size tool:

![capture](https://user-images.githubusercontent.com/1930029/140533681-a8e292b0-bfa9-4b33-b183-3d9d700480f5.png)

Obviously there are a lot of tools left to convert, and each one will likely bring new challenges, but it's a start!

**Comment by tannerhelland** [comment]
As of December 2021, the new toolbar design is available in nightly builds.  Many thanks to @Kroc for suggesting this improvement!
