### ISSUE TITLE
avif file support ?

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#340]
Hello, 

Today,  the last update of  Paint.net introduces the .AVIF file format . so, I discover this new image format which appears very interesting and open source . Did you knew this file format ? Will it be possible to implement it in Photodemon ?

**Comment by tannerhelland** [comment]
Hi @mizka76.  Thank you for this good suggestion.

The new AV1 format support in Paint.NET was contributed by an outside developer: https://github.com/0xC0000054/pdn-avif

If I am fortunate to have an outside developer contribute a similar library to PhotoDemon, I could add support very quickly.  But if I have to study the new format and develop the feature myself, it is a much longer (and harder) road.

Another option is if [the open-source library libavif](https://github.com/AOMediaCodec/libavif) starts publishing prebuilt shared libraries for Windows.  I could tie those into PhotoDemon relatively easily, but at present, they do not provide prebuilt Windows DLLs.  I will keep an eye on this project to see if this changes in the future!

**Comment by vatterspun** [comment]
This is one of those chicken-and-egg situations where if viewers/editors like PhotoDemon support the format, it's more likely to catch on but then do you want to chase every new format that comes out?  HEIC for example basically took over my iPhone but I almost immediately turned it off because of lack of support by other devices, even inside the Apple software ecosystem.

Still, in terms of replacing JPEG, I do have faith that AVIF will beat out a lot of other options that either have royalty requirements or patent issues, but things seem to be moving slowly in terms of viewers.  The wikipedia page has a good summary of the format and support: https://en.wikipedia.org/wiki/AV1#AV1_Image_File_Format_(AVIF)

**Comment by tannerhelland** [comment]
Also, I also don't think that anyone has created an AVIF library that works all the way back to Windows XP.  This lack of backward-compatibility is always tricky for PhotoDemon.  (For example, I silently enabled HEIC support in PD's 8.0 line of releases, but it only works on Win 10 because it relies on Windows to supply the patent-protected decode library, and Microsoft only does that for certain Win 10 builds... I hate these kind of "secret" support levels, but it remains a necessary curse of open-source work.)

**Comment by wqweto** [comment]
I don't see x86 support in libavif because there is no x86 support in Google's [aom](https://aomedia.googlesource.com/aom) it seems. At least I couldn't find the x86 assembly optimized AV1 codec, there is only x64 version.

If Microsoft provides AVIF support for x86 versions of Win10 that would be a first, although I doubt it.

**Comment by tannerhelland** [comment]
Just a quick note that [current AVIF encoders are hilariously inefficient](https://0xc0000054.github.io/pdn-avif/using-image-grids.html).  From the linked article (by the author of paint.NET's AVIF plugin):

> As of version 2.0.0 the AOM encoder is very memory hungry, when saving a 4032x3024 pixel image without using an image grid I noticed in task manager that it was using approximately 2.5 GB of memory on speed 6 with Realtime usage. The AOM encoder also lacks the ability to cancel an encode operation that is in progress.

**2.5 gigabytes** of memory just to encode a 12-megapixel photo is insanity.  That kind of memory usage might explain why no one is attempting x86 support yet.

**Comment by tannerhelland** [comment]
PhotoDemon's latest nightly builds now provide full support for loading and saving AVIF images.  The open-source [libavif library](https://github.com/AOMediaCodec/libavif) provides the underlying AVIF interface.  

Note that AVIF support only works on 64-bit Windows installs because libavif doesn't support 32-bit configurations.  PhotoDemon automatically detects this and modifies its behavior accordingly.  Multi-threaded encoding and decoding is available and will automatically be activated when relevant.  Note also that a *lot* of memory may be required for even medium-sized AVIF images, as discussed earlier in this thread.

Please let me know if you encounter any issues with AVIF files!  (And thank you to @mizka76 for originally suggesting this feature.)

(Note also that I've submitted some feature requests to the libavif authors that will improve performance when loading and saving AVIF files from PD; these feature requests are already merged into the main libavif repo, but won't be available until the next official libavif release).
