### ISSUE TITLE
[Feature request] - (i have a good RGB to LAB algorithm)

### ISSUE THREAD

**Issue by loquat** [tannerhelland/PhotoDemon#348]
i have found a good RGB2Lab as well as LAB2RGB algorithm here created by laviewpbt
http://files.cnblogs.com/Imageshop/ImageInfo.rar
maybe you can ues it to upgrade some of the functions in Photo Demon
Tips as the original article indicates here
https://www.cnblogs.com/Imageshop/archive/2013/02/02/2889897.html
"Using this fast algorithm to perform multiple conversions, there must be a loss of accuracy."
but i have not tried to search more articles from laviewpbt about this.

**Comment by tannerhelland** [comment]
Hello @loquat.  Thank you for this suggestion!  I am very impressed with laviewpbt's work.  

PhotoDemon currently uses [the LittleCMS library](https://www.littlecms.com/) for its LAB transforms.  This is necessary for color-management purposes because RGB is not an absolute color space, so you can't directly convert between RGB and LAB without color reproduction issues.  An absolute color space like sRGB or Adobe RGB must be used (and your RGB data must already exist in such a space) before a LAB transform can be used correctly.  PhotoDemon manages all of this "beneath the surface".

PhotoDemon currently uses LAB transforms in a number of places to improve quality; for example, the `Effects > Stylize > Palettize` tool supports using LAB matching for improved palette behavior, while the `Effects > Noise > Median` tool can be applied to just the luminance channel (using a LAB transform as well).

PhotoDemon also supports LAB transforms from image files that support it, e.g. PhotoShop PSD files in LAB color space can be loaded into PhotoDemon just fine.

I hope this information is helpful!
