### ISSUE TITLE
[Feature request] - Batch export 

### ISSUE THREAD

**Issue by TyraVex** [tannerhelland/PhotoDemon#378]
Hello,

It would be very nice to have the option to export batch images to their original location
For example, when selecting images from an entire folder (subfolders included), there is no automatic way to edit them all and save them in the same subfolders they are in. You currently need to move them manually to their respective folders if you want to do that
And if you could add the option to overwrite the original images with the edited ones it would be even better :)

To give you a bit of context of why I'm asking this is because I want to set the transparency to 50% of all the images in some subfolders.

Have a great day!

**Comment by tannerhelland** [comment]
Hi @TyraVex .  Thank you for another great feature suggestion.

I am **really** nervous about an option to overwrite original images in the batch processor, simply because there is a potential for losing a *lot* of data if PhotoDemon crashes.  (And the batch processor is incredibly complex, so crashes are... well, "not likely" but also "not impossible".)

That said, the current approach of completely losing subfolder organization is also pretty bad, so I've now added a checkbox on the last page of the batch wizard:

![image](https://user-images.githubusercontent.com/1930029/139504871-f2fca5f1-e37f-4f78-a263-b1ef86928491.png)

Check that box, and PhotoDemon will now create an identical folder structure in the destination folder, and all processed images will be automatically sorted into their same folders.  After processing finishes, if you **really** want to overwrite your original copies (please double-check that everything looks okay first), you can just Copy+Paste the destination folder over your original folder and everything will match up 100%.

I hope this solution is "good enough"!  I am going to leave this issue open for a few days while I stress-test the new code to make sure it can handle all kinds of weird folder arrangements, and of course if you have any additional feedback, please let me know.

Thank you again for suggesting this much-needed improvement 🙏

**Comment by TyraVex** [comment]
Thanks a lot for this new option! 
I will try it tomorrow but I think it will be as good as the overwrite option I suggested before :)

**Comment by TyraVex** [comment]
It's working very well, thanks a lot!

**Comment by tannerhelland** [comment]
Thank you so much for the follow-up, @TyraVex !

As a "thank you" for all your help with this (and the previous issue), I am happy to add you to the contributor list for the next release.  Just let me know what name and/or website you'd like me to use.  (I can also use your GitHub name and user page if that's preferable.)

**Comment by TyraVex** [comment]
> Thank you so much for the follow-up, @TyraVex !
> 
> As a "thank you" for all your help with this (and the previous issue), I am happy to add you to the contributor list for the next release. Just let me know what name and/or website you'd like me to use. (I can also use your GitHub name and user page if that's preferable.)

Wow, thanks!
You can use my GitHub name and profile for that :)
