### ISSUE TITLE
Possible improvements for selection tools

### ISSUE THREAD

**Issue by manfromarce** [tannerhelland/PhotoDemon#395]
### Version information
 - PhotoDemon 9.0 pre-alpha (build 1327)
 - Windows 11 21H2 (22000.556)

### Description and screenshots
Thank you for your great work, PhotoDemon is a good open source alternative to Photoshop and Paint.Net.
I just want to suggest some small improvements for selection tools and report a possible bug:

1. In my opinion, when the selected area is moved 2 or more times consecutively PhotoDemon could create a new layer only the first time and not every time, or it could have an option/checkbox to never create a new layer when the selection is moved, like in Paint.Net (maybe I'm wrong, but I couldn't find this setting)
2. If you click on the selection with the Move tool and then click again and drag the selection, an empty layer is created in addition to the selection layer. Maybe empty layers could be skipped.
![screenshot](https://user-images.githubusercontent.com/45036600/157850009-16f5a93f-7f4e-400d-a925-b6760d8b3ddd.gif)
3. In some SVG files with small resolution, if the zoom level is increased the magic wand selection appears to be "shifted" by 1-2 pixels because it also selects different colors even though the tolerance is set to 0
![screenshot](https://user-images.githubusercontent.com/45036600/157858042-b89b919f-91d6-4625-8fd9-98d40527bcb8.gif)

**Comment by tannerhelland** [comment]
Thank you so much for this detailed bug report, @manfromarce .  The screen captures are especially helpful.

To be honest, I have not spent enough time studying the "drag selected pixels" behavior in other software, and the current PhotoDemon implementation shows that.  I will start investigating these issues right away.

**Comment by manfromarce** [comment]
Thank you @tannerhelland for your quick fixes, everything seems to be working fine now

**Comment by Kroc** [comment]
In PSP7, selecting pixels and then dragging them creates a temporary pseudo-layer called "floating selection"; this allows for easy moving the pixels a second time without affecting the original image. When the user clears the selection, it gets merged down, however a user can right-click the temporary layer and choose "promote to layer" to make it a full layer. This is a little clumsy and non-obvious but is an example of one way floating selections are handled.

**Comment by tannerhelland** [comment]
Thank you for the follow-up @manfromarce !  I'm glad we got this fixed.

@Kroc Photoshop and GIMP work similarly.  (Photoshop will even save the current floating selection into your PSD, if you try to save while a floating selection is active.)

It's an interesting historical artifact since floating-selections were added to most of these programs before layers were!  I assume that's why floating-selections are treated as a weird "special layer case" in these apps with their roots in the early 90's.

It would be a huge effort in PhotoDemon to add a similar "special-case" layer for floating-selections, since every tool/adjustment/effect/menu/etc would need to be updated to handle it.  It was much easier for me to just create a new layer when moving selected pixels, since I already had UI for that, including resizing/rotating/transforming the selected pixels post-move.
