### ISSUE TITLE
[Other] - (I need help of White Rebalance)

### ISSUE THREAD

**Issue by HanalogInstruments** [tannerhelland/PhotoDemon#408]
Hi,

I have recover some jpeg encrypted by ransomware but the DQT Tables maybe wrong, i wanna to know how to make batch White Rebalance for jpeg with PhotoDemon via command line:

Also jpeg have black MCU on top how we remove it automate and White Rebalance?

![_20151030_194834](https://user-images.githubusercontent.com/100456607/171441361-de77d3ff-5311-4a3f-a070-274221f4c24f.jpg)
![_NHL0590](https://user-images.githubusercontent.com/100456607/171441370-f82bc0dc-bf62-43e2-a4a9-96aede3a07b5.jpg)
![_NHL0591](https://user-images.githubusercontent.com/100456607/171441377-889900e5-2df9-43ce-a419-c82d53550bc1.jpg)
![110A8527](https://user-images.githubusercontent.com/100456607/171441384-10c179b0-2ba7-4f04-ad99-6f7a32d8f7ed.jpg)

**Comment by hi5** [comment]
Not sure if cmd line is possible but I would probably create a macro for the white balance and then use **File, Batch operations** to select all files and process them. 

In the macro below I also create a large selection trimming the top part of the image - which works for the first image above - the white balance may be hit and miss as some need a bit more and some a little less so I would do them all - see which one need a bit more work and select those with another macro and so on - hopefully that is manageable

[crop-and-white-balance.zip](https://github.com/tannerhelland/PhotoDemon/files/8818373/crop-and-white-balance.zip)

P.S. If you really want command line I would suggest image magick, here is is a white balance script http://www.fmwconcepts.com/imagemagick/autowhite/index.php

**Comment by HanalogInstruments** [comment]
Hi, 

How is that crop macro working? maybe i need to find solution in python to crop and white balance

**Comment by hi5** [comment]
I just drew a rectangle selection beneath the black bar, cropped the image, then executed white balance - from the history I created the macro and ran it on several images and seemed to work OK-ish.

**Comment by HanalogInstruments** [comment]
> Hi,
> 
> 
> 
> I have recover some jpeg encrypted by ransomware but the DQT Tables maybe wrong, i wanna to know how to make batch White Rebalance for jpeg with PhotoDemon via command line:
> 
> 
> 
> Also jpeg have black MCU on top how we remove it automate and White Rebalance?
> 
> 
> 
> ![_20151030_194834](https://user-images.githubusercontent.com/100456607/171441361-de77d3ff-5311-4a3f-a070-274221f4c24f.jpg)
> 
> ![_NHL0590](https://user-images.githubusercontent.com/100456607/171441370-f82bc0dc-bf62-43e2-a4a9-96aede3a07b5.jpg)
> 
> ![_NHL0591](https://user-images.githubusercontent.com/100456607/171441377-889900e5-2df9-43ce-a419-c82d53550bc1.jpg)
> 
> ![110A8527](https://user-images.githubusercontent.com/100456607/171441384-10c179b0-2ba7-4f04-ad99-6f7a32d8f7ed.jpg)
> 
> 

@tannerhelland Could you made a commandline version of photodemon on windows to run the macro?

**Comment by tannerhelland** [comment]
I agree 100% with the excellent advice from @hi5 - use ImageMagick if you need a cli tool for batch processing.

Windows does not allow the same app to operate as both a console and GUI application.  This is a long-standing Windows issue with no clean workarounds:

https://www.tillett.info/2013/05/13/how-to-create-a-windows-program-that-works-as-both-as-a-gui-and-console-application/

It would be a significant project (multiple years of effort) to split PhotoDemon into separate console- and GUI- components that could be used independently.  I would rather spend that time adding new features and improving existing features, especially because ImageMagick already exists as an extremely powerful cli image processor.

PhotoDemon's batch processor does allow you to process multiple images and/or entire folders at once, even folders from separate drives or network shares.  You can also save a list of images for future or report processing.  This, combined with extensive support for recording macros, is as much automation as I can reasonably support right now.

Thank you to @hi5 for providing excellent help in this thread.
