### ISSUE TITLE
Out of memory saving JPG

### ISSUE THREAD

**Issue by Petomai** [tannerhelland/PhotoDemon#413]
### Version information
 - PhotoDemon version 8.4
 - Windows Version 11

### Describe the bug
Saving to JPG results in out of memory error. 

### How to reproduce the bug
Open an image file. 
Click the Image menu
Canvas Size
resize canvas height only to 34000 (Error! unable, can only 32760)
resize height to 32760
add many individual images as new layer down the height of 32760 until it is full
add new black layer as background
crop image to selection to clear away black areas
save as JPG. Out of memory error. 

### Expected behavior
I would expect image to save. I have 32GB RAM no need for out of memory. I have 1TB HDD for virtual memory if needed. No need for out of memory. 
### Debug logs
debug folder empty
![Screenshot 2022-06-07 012323](https://user-images.githubusercontent.com/4734703/172332878-e825999d-6f04-4bdd-96d2-c17ccd4fe892.jpg)

**Comment by Petomai** [comment]
10 layers plus 11th layer for black background. This is financial data needed to string along one image for sending to financial institution.

**Comment by Petomai** [comment]
> Hello @Petomai You report an error in adjusting image 34000, only 32760 is supported. This error is not an error in PhotoDemon, but a limitation of Microsoft Visual Basic 6.0 code functions. Photoshop will not adjust image 34000. The development language used is not limited by code functions, and parameters can be set of infinity.

This was not my report. Please review again.

**Comment by shishi2019** [comment]
@Petomai terribly sorry! I'm just replying to you according to the error description you sent, what I said is my personal opinion, not the personal opinion of @tannerhelland

**Comment by shishi2019** [comment]
Microsoft Visual Basic 6.0 was released in January 1999, and the Windows system is constantly updated. Many code functions of Microsoft Visual Basic 6.0 cannot be supported by Windows. In order to develop better functions in Microsoft Visual Basic 6.0, it is necessary to use DLL to encapsulate functions. Called in Microsoft Visual Basic 6.0 code. But the workload is very large. I believe @tannerhelland will not spend such a large amount of work to encapsulate functions in DLL for the time being. The image size can be arbitrarily set to be infinite. I believe that PhotoDemon will be able to arbitrarily set the image size like Photoshop in the future.

**Comment by tannerhelland** [comment]
Hi @Petomai .  PhotoDemon's README file includes this disclaimer:

## Limitations

-  Due to its portable nature, PhotoDemon is only available as a 32-bit application.   (This means it cannot load or save images larger than ~2 GB in size.)

Because many program operations require multiple copies of an image (e.g. JPEG saving requires translating the image to YCbCr color space before saving), you should ideally keep image sizes well below 1 GB.  Your sample file of 32760x4400 requires more than 500 MB per layer, so it exceeds the amount of memory allowed to a 32-bit application like PhotoDemon.

Unfortunately, I cannot work around this without breaking PhotoDemon's portable nature.

If you need to work with extremely large images, I would recommend GIMP or Paint.NET instead.  Both are available in 64-bit versions that can address terabytes of memory, but note that they only work on modern, 64-bit versions of Windows.
