### ISSUE TITLE
[BUG] - Edit -> Repeat <effect> not working

### ISSUE THREAD

**Issue by YouveGotMeowxy** [tannerhelland/PhotoDemon#423]
### Version information

Please include both the PhotoDemon version (found in the `Help > About` menu) and Windows version, if you know it (e.g. "Windows 11").

9b 1707

### Describe the bug

- "repeat <effect>" does nothing.

### How can I reproduce the bug?

1. I select an area w/selection tool, use an effect, such as Blur box, it blurs the selection.
2. I select another area, go to edit -> repeat Blur box ... nothing at all happens.

### Expected behavior

When I try to repeat the effect, it repeats it.

Additionally, it would be great to have a shortcut key for this. Also, going on memory, I think photoshop has it's "repeat effect" right as the top menu item in the same effects menu where it's a little bit more intuitive to go back to when applying an effect, than over to the "edit" menu. :) (a separate menu)

### Sample images and/or screenshots

It happens with any image.

**Comment by tannerhelland** [comment]
Your bug reports are always so helpful, @YouveGotMeowxy !  Thank you for reporting this.  I've tracked down the cause and will have a fix ready soon.  

I'm especially glad you reported this bug because there are quite a few problems with the `Repeat last action` command and the new selection engine, yikes!  Thank you again!

> Additionally, it would be great to have a shortcut key for this. 

I will look for a good shortcut combination.  Photoshop doesn't have a shortcut for their repeat action (alas), so I'll check other software to see if there's a consistent convention for this.

> Also, going on memory, I think photoshop has it's "repeat effect" right as the top menu item in the same effects menu where it's a little bit more intuitive to go back to when applying an effect, than over to the "edit" menu. :) (a separate menu)

I completely agree, but PhotoDemon's current `Repeat Last Action` works on actions from *all* menus - not just Effects!  That's how it ended up in the Edit menu.

In the next release, I'll look at adding a dedicated `Repeat Last *Effect*` (and `Re-show Last Effect Dialog` like GIMP - I like both!) to the Effects and possibly Adjustment menus, to better improve discoverability for Photoshop users.  Thank you for mentioning this.

(Now back to work fixing this `Repeat last action` nightmare 😵‍💫 )

**Comment by tannerhelland** [comment]
Thank you again, @YouveGotMeowxy !  A fix is now available in the latest nightly build.  `Edit > Repeat` should now behave as intended.

I am still studying the best hotkey combination for that command and will hopefully add one soon.

I have also made a note in my post-9.0 roadmap to get dedicated "Repeat" and "Re-show" commands added to the Adjustment and Effect menus.

**Comment by YouveGotMeowxy** [comment]
Wow, that was super fast! Ever dev should be like you; super fast and a great attitude! :D
