### ISSUE TITLE
clone tool ( from  "image") not accurate after deleting part of an image 

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#449]
### 
( first,  you made with Photodemon 9 a very impressive software , amazing work !! )
here a little bug i think :  I often resize and clear off  the background of *.jpg images , make sometimes corections with the clone brush and save them as png... I noticed that after deleting a part of the image with the magic wand, the clone brush is no more accurate , there is a différence between the chosen origin  of the clone tool and the part of the image it paints with . 

###
 here a example where the origin zone with the clone tool and what it has done  when the cloning source is "image" ( but it . works fine when i choose "layer" as clone source . Dont know if it is a normal behaviour. 

### Thank you! 

![cloning after backgronud delete with magic wand (14 octobre 2022)](https://user-images.githubusercontent.com/62914748/195915612-19841cb1-0987-46e9-9c04-693d9bdc2001.png)

**Comment by tannerhelland** [comment]
Hello @mizka76 .  You continue to impress with your bug-detection skills!  Thank you so much for finding and reporting this problem.

I have tracked down the cause and hope to have a fix available soon.  (Other software resets the clone brush after image size changes, and I think that will be the best solution for PhotoDemon too.)

I will send word when the fix is available.  Thank you again 🙏

**Comment by tannerhelland** [comment]
Thank you again for this bug report @mizka76 .  I believe I have fixed the bug in the latest nightly build (uploading now).  

(I'm especially happy you found this because a similar bug affected the Measure tool.  It also needs to be reset after changing image size!)
