### ISSUE TITLE
Crashes when using Brightness and Color Contrast

### ISSUE THREAD

**Issue by opsimathic** [tannerhelland/PhotoDemon#452]
Photodemon 9.0
Windows 10

Program crashes when editing relatively large jpg file and trying to adjust Brightness and Color Contrast.  Program simply stops and I get kicked out to my windows 10 home page.  Does NOT occur for small files. 

Again, the more detailed, the better.  A clear list of steps is especially helpful:
   1. Open large jpg file (example approx 5000 x 3300 px)
   2. Click on Adjustments and then Brightness and Color Contrast
   3. Makes change to both Brightness and Contrast
   4. Press OK and voila program crashes.
![PD crash error message](https://user-images.githubusercontent.com/116322793/197089674-14910b5b-e90e-4b46-aa3c-e4667b23b6b1.jpg)

   5. Open up PhotoDemon again and usually there is a problem encountered message - will try to attach screenshot
  

### Expected behavior

Please describe what *should* happen.  Should return me to the main PhotoDemon page

### Thank you!

As a "thank you" for your help, I am happy to add your name to PhotoDemon's contributor list.  Please let me know what name (and optional website link) you'd like me to use.

**Comment by tannerhelland** [comment]
Hello @opsimathic .  Thank you for reporting this.  I'm sorry PhotoDemon is crashing for you!

I have tried to replicate this issue but unfortunately I have not succeeded (yet).  I have even tried significantly larger images than the size you mentioned (5000 x 3300), and still haven't encountered any problems.

Can I ask you to attach a Debug log of the problem?  Start PhotoDemon, then go to the Tools > Options > Advanced panel.  Toggle the "generate debug logs" option to ON (instead of Auto).

Now assuming you can replicate the bug, go ahead and run PhotoDemon, repeating the brightness and contrast steps until it crashes.  

Then...

1) Open Windows Explorer
2) Navigate to your PhotoDemon folder
3) Navigate to the `/Data/Debug` subfolder.  There should be one or more files with the `.log` file extension.  
4) Find the **most recent** log file (you can click the "Date Modified" column header to sort by date and time) and drag it to the comment box on this GitHub page.  GitHub should automatically attach it.

That debug log is just a text file (you can read it in Notepad if you're curious) and it will contain additional info that may help me track down the cause.  At present, I'm guessing it may just be low RAM on your system and the function is running out of memory, but it could be something else - the debug log will help.

Thank you!

**Comment by opsimathic** [comment]
Thanks again for your quick response.

I have managed to replicate the issue and the debug log is attached
(debug_report_0).

I then changed from Legacy to Modern and could not replicate the error
again.  So this may be an issue with the Legacy version of Brightness and
Contrast but not with the Modern version.  This significantly reduces any
urgency (for me at least) as I can simply use Modern. 😀

I have also attached the debug_report_1 when the software did NOT crash
because I was using Modern.

Hope this all helps.
Thanks again!
*/John*

John Cassels - Missions Advocate
Africa Inland Mission
*Christ Centered Churches Among All African Peoples*
*www.aimint.org/ca <http://www.aimint.org/ca> *

*Canada (Sep2022-Apr2023)*
32 Thornbush Crescent, Waterloo ON, N2T 1B2 Canada
Ph: +1-226-868-9782 (Krys)
Ph: +1-226-978-9506 (John)
*Uganda (Apr2023-Aug2023)*
Soroti, Uganda
Ph: +256-779-240-572 (Krys)
Ph: +256-785-741-179 (John)

**Comment by tannerhelland** [comment]
Thank you so much for the follow-ups, @opsimathic.  GitHub unfortunately does not allow attachments via email reply, but that's okay because your observation that the bug only occurred in the "legacy" brightness/contrast adjustment was exactly what I needed.  The underlying problem has been found and fixed!

Feel free to download the latest PhotoDemon nightly build at your leisure.  It will include this fix and a few others added since 9.0.

Thank you again for your help with this.  🙏
