### ISSUE TITLE
[BUG] - batch convert svg does not work

### ISSUE THREAD

**Issue by veksha** [tannerhelland/PhotoDemon#456]
### Version information

PhotoDemon 9.0.50
Windows 11

### Describe the bug

batch converting svg format does not work. I need to convert a lot of svg images to png and resize them.
but PhotoDemon hangs/crashes.

### How can I reproduce the bug?

press ctrl+b and select all options to convert even 1 svg file to png (resizing to 64x64 for example)

### Expected behavior

no crash

### Debug logs

[DebugReports.zip](https://github.com/tannerhelland/PhotoDemon/files/10014066/DebugReports.zip)

### Sample images and/or screenshots

screen before crash:
![image](https://user-images.githubusercontent.com/275333/201962765-365df140-8e27-4a9e-ba91-084f2e8ecb36.png)

**Comment by tannerhelland** [comment]
Hello @veksha .  Thank you for catching and reporting this.  I apologize for broken SVG behavior during a batch process.

I have just uploaded a new nightly build that fixes this problem.  (I tested the fix with a batch process on a folder tree of ~15,000 SVGs and everything completed successfully.)

Please let me know if you encounter any other problems with batch processing SVGs.  Thank you!

**Comment by veksha** [comment]
thanks, @tannerhelland! now all works. but I have a question.
why PhotoDemon (and XnConvert, btw) converts SVG to PNG with low quality?
it takes into account dimensions that are specified inside svg file (32x32 pixels) ?

i think PhotoDemon (and XnConvert) first does conversion to png using specified dimension 32x32  and then to whatever size I choose in resizing action. (64x64 for example)

and intead of:
![image](https://user-images.githubusercontent.com/275333/202054744-f814866b-e512-4c56-a103-b0303cbf7fa1.png)

we get:
![image](https://user-images.githubusercontent.com/275333/202054803-400624e6-18bf-478b-8988-4769851409fc.png)

first screenshot is svg converted using `batik-rasterizer` (nice command-line tool which can convert SVG to PNG)
second screenshot is PhotoDemon (XnConvert gives similar quality)

I think user expects to get best quality possible, while rasterizing vector formats.
what do you think, @tannerhelland?

attaching this svg file: 
[file_type_antlr.zip](https://github.com/tannerhelland/PhotoDemon/files/10017116/file_type_antlr.zip)

**Comment by tannerhelland** [comment]
Thank you for the quick reply, @veksha .

For your follow-up comments, the problem is less a technical one and more a user-interface one.

When you load an SVG into PhotoDemon, you receive a prompt asking how large you want the image to be:

![image](https://user-images.githubusercontent.com/1930029/202202709-c325a813-1d80-4d5e-9220-a537f8d43407.png)

PhotoDemon has to maintain the image internally as a traditional raster surface, so the user can do things like paint on the SVG or apply adjustments and filters to it.  (A small command-line tool like batik doesn't have this concern, so it will operate purely on vector data until the final save operation.)

During a batch conversion, however, I can't pop up that import window for every single image!  So PhotoDemon just has to "guess" at what SVG import size to use, and that inevitably means using the suggested size inside the SVG file.

I don't know a good way to solve this.  I could possibly add an additional page to the batch process wizard, where the user can set import options for formats like SVG?  I am open to other suggestions.

**Comment by veksha** [comment]
Thank you for answer, @tannerhelland.

If I understand correctly, rasterization of vector format happens on import and then resize action takes place.
bad bad bad. Can't think of a user who wants such behavior from batch converting/resizing tool.

If user haven't specified to which dimensions to resize all pictures (he just wants to rasterize without resizing), then we can rasterize on import (using embedded dimensions data). right?

but if user wants to batch rasterize and resize pictures, we must somehow do this resizing only once. agree?
no one will ever need (no one expects) two-stage resizing.

**Comment by tannerhelland** [comment]
Yes, I certainly do agree that resizing once would be ideal.

The problem is always **how to make this possible**?

A program like PhotoDemon is compartmentalized into many individual components.  These components cannot really talk to each other.  

The image loading part of the program just loads an image as-is.  It was designed for raster images (per the program name) so it uses the default size specified in the image file, which is how 99.9% of image files work.  For SVG images, it asks the user what size to use.

The image loader has no idea what will happen next.  It cannot predict that a resize will happen later.  As much as I wish otherwise, it is not psychic!  😄  

So for your specific request, I need to write new code in the batch process engine that scans the full list of batch process commands, looks for any resize events, finds the largest one, and then uses that image import size - but *only* for SVGs and *only* during batch processing (otherwise the user must be prompted).  This will require a lot of new code and the image importer must now support custom size requests from the batch process tool, which is a significant change.

I can of course add this, but like all special features it takes time and effort.  I will do my best to tackle it soon but please be patient - image import is a sensitive part of the project, and I have to work carefully so that I do not break anything.  Playing with image sizes like this can have many unforeseen side-effects so I'll need to exert extreme caution.

I will report back when I have a new version to test.

**Comment by veksha** [comment]
Hi, @tannerhelland.

> looks for any resize events, finds the largest one, and then uses that image import size

why find largest one? user may want to specify 512x512 import size to work with more pixels (more quality), while the largest one may be too small (like 64x64) and rasterization will be of poor quality.
adding a little option like "override import dimensions" to batch dialog will be enough, I think. and a text label explaining that it can lead to higher quality rasterization.

another way is to not implement this and just add a simple warning like "embedded image size of SVG file will be used. it may result in lower quality images. better use other tools (like batik-rasterizer.)" 😄 

anyway, thank you for time and attention. it would be cool if this feature will be implemented in the future. but until that time simple warning can be enough. :)

**Comment by tannerhelland** [comment]
why find largest one? user may want to specify 512x512 import size to work with more pixels (more quality), 
     while the largest one may be too small (like 64x64) and rasterization will be of poor quality.

     adding a little option like "override import dimensions" to batch dialog will be enough, I think. and a text 
     label explaining that it can lead to higher quality rasterization.

Thank you for the additional clarification, @veksha .  I will add a size override option like this instead.  I misunderstood that you could want a larger "intermediate size" for working on the SVG.

I just have to reiterate that rasterization only happens once - when the SVG is first loaded.  Beyond that point, the file will be a raster image and all operations will be raster ones.

So if you want to e.g. do this as a batch process:

- Load SVG at override size requested by user (e.g. 512x512 )
- Rasterize SVG (convert to normal pixel image - this is mandatory to edit the pixels in PhotoDemon)
- Apply filters or changes to image
- Downsize to 64x64  <--- This step will obviously use raster downsampling
- Save to new file format (like PNG or whatever)

That final downsize must use raster downsampling.  I just want to confirm that is okay before adding this "override import size" option?

**Comment by veksha** [comment]
Yes. I don't see no other way to do it better.
the bigger initial dimensions the more quality of downsizing to 64x64.

**Comment by tannerhelland** [comment]
Thank you for the kind words, @veksha !  I really appreciate your help and patience on this issue.
