### ISSUE TITLE
[Feature request] - Content Aware Fill needs better settings.

### ISSUE THREAD

**Issue by jointri** [tannerhelland/PhotoDemon#458]
### Is this feature request related to a problem? 

It's frustrating to use the content aware fill at times because there is no clear indication of how the settings work. What does outside-in and inside-out mean? What does random patch candidates do? There should be an explanation of what each setting does, because it's not clear at all what they do and it makes experimenting hard.

### Describe the best way to implement this.

Add explanations of what the settings do. I really need this because it makes it difficult to use the content aware fill.

### Thank you!

No credit is necessary, I just would like to improve the content aware fill.

**Comment by tannerhelland** [comment]
Hi @jointri .  I apologize that it has taken me some time to reply.  (Last week was a holiday week here and I did not have much time for PhotoDemon work.)

I would love PhotoDemon to have better documentation, but I simply do not have time to create in-depth documentation at present.  Outside help would go a long way, but there are not many people who can spare the time to document a project of this size!

In PhotoDemon's content-aware fill tool, "outside-in" and "inside-out" appear under the "fill order" title.  As the title suggests, these settings control the order in which pixels are replaced ("filled") by the tool.  "Outside-in" starts at the outer edges of your region; "inside-out" starts at the center of the region.  "Random" replaces pixels in a random order.  

PhotoDemon is based on the "Resynthesizer" algorithm by Paul Harrison: https://logarithmic.net/pfh/resynthesizer .  Dr Harrison found that random order worked best for most patches (as discussed in his PhD thesis at that link) because it produces novel textures that "disappear" nicely into the surrounding regions of the image.  However, strong repeating patterns may synthesize better with "outside-in" or "inside-out" order, depending on the shape of the region, because the synthesizer can precisely match existing pattern elements instead of synthesizing a new pattern from scratch.  

I added these fill order options manually after extensive testing against various fixed patterns.

"Random patch candidates" is how many patches the program test-synthesizes for each pixel.  Higher numbers will run much slower but potentially produce better results.  The "patch test size" works similarly - each pixel must be tested against a number of neighboring pixels in each potential synthesized patch.  Testing more pixels takes more time, but can produce a better texture, at a significant penalty to performance.  

I hope this information helps.  I will close this issue for now as I do not have time to write up extensive documentation for this tool.  Paul Harrison's thesis is the definitive resource on this method of content-aware filling, and it is 140+ pages long - so this is a complex topic that is not easily summarized in just a few lines.

Ideas for better names or text on the too itself is always welcome, and you are of course free to ask questions here - I will do my best to answer as I can.

Thank you!
