### ISSUE TITLE
[BUG] - Inconvenience with de-marking/de-selecting scroll bars, which were marked/selected, to make CTRL-Wheel Zoom work again.

### ISSUE THREAD

**Issue by 0lm** [tannerhelland/PhotoDemon#476]
### Version information

Windows 10. PhotoDemon 9.2 pre-alpha (build 145)

### Describe the bug

Not sure if it is a bug, or just some feature inconvenience. Usually I can zoom in/out the image by holding CTRL pressed and then rolling the mouse wheel. But when a certain action is done before, it locks itself and it isn't possible anymore, until you click another tool feature.

### How can I reproduce the bug?

The bug is probably reproduceable in different ways. I will tell here the way I encountered it:

1. when you click one of the bars (the ones for manually scrolling a big image from left to right, or from up to down. these bars are on the bottom or right side), then this bar gains focus, which marks it blue.
2. When it is marked blue, CTRL -Wheel Zoom wont work, but only Wheel-Scrolling will work to the direction based on the functionality of the bar (e.g. if you click the bottom bar, marking it blue, for left-right scrolling, then mouse wheel will only scroll left-right.) - up to now, this behaviour makes total sense
3. The issue starts here: To de-select/remove the bar marking, I need to select a different tool. Or re-select the same tool I was/am currently working with.

### Expected behavior

As it is now, the workarounds are easy, but at the same time, too time-consuming when needing to select a different tool, or re-selecting oyour current tool. Especially when someone works alot with zooming and scrollings. It would be much easier to de-select the bar marking with a button like ESC. Or at least if we were able to deselect the marking, by re-clicking on the marked bar, to lift the marking form it.

**Comment by tannerhelland** [comment]
Hello @0lm .  I apologize that it has taken me so long to address this issue.  A littany of health and personal issues has interfered with my open-source work this year, and I am just now starting to catch up on old PhotoDemon issues.

I just uploaded a new nightly build that allows you to press ESC when the canvas scrollbars have focus.  This will remove focus from the scrollbar, and return it to the image canvas.

Whenever possible, I need to adhere to traditional Windows rules for [focus](https://en.wikipedia.org/wiki/Focus_(computing)) (the on-screen object with "focus" is the object that currently responds to keyboard events - usually the last object you clicked on).  Because clicking on an on-screen object is the universal mechanism for *applying* focus, a new feature where clicking a scrollbar twice *removes* focus would produce wildly different behavior than other Windows controls.  I would like to avoid this.

I am open to any other suggestions for improving PhotoDemon's interface, as long as it doesn't deviate too far from "normal" Windows behavior.

Thank you again for your suggestion and patience with this issue 🙏
