### ISSUE TITLE
[bug] PhotoDemon 9.2 pre-alpha: Writing Multi-Layered TIFF error

### ISSUE THREAD

**Issue by hi5** [tannerhelland/PhotoDemon#508]
**First of all:** I'm really happy with the way PD reads multi-layered TIFFs, many graphic programs can't handle it properly, PD can!
**Second:** I don't consider this a serious but as I suspect there might be something "off" with the way I create the TIFFs, but I thought it was worth reporting anyway. Perhaps there is an easy fix.

### Version information

PhotoDemon 9.2 pre-alpha (all builds I think). Windows 10, Windows 11

### Describe the bug

I'm using [GraphicsMagick ](http://www.graphicsmagick.org/) - an ImageMagick fork - to create a multi-layer TIFF (samples attached)

PD opens these perfectly and I can edit them - I often just need to move the top layer into position. I then save the result as JPG or PNG which works perfectly of course.

But there is an error when saving it back as TIFF. It works to save as a flattened TIFF, but keeping it multi-layered doesn't work and shows

```
An unspecified error occurred when attempting to save this image.
Please try saving the image to an alternate format.

If the problem persists, please report it to the PhotoDemon developers
via photodemon.org/contact
```

At first I thought it was because the base layer I was using was only 8b `output1.tiff`, but it happens with 24b too `output2.tiff`

### How can I reproduce the bug?

TIFF files: [tiff.zip](https://github.com/tannerhelland/PhotoDemon/files/13688471/tiff.zip)

Open one of the TIFFs, Save as TIFF, just be sure to select Multi-page TIFF (basic settings in the Save) - file isn't saved and error message (above) is shown.

NOTE: when I use a test image from [elsewhere](http://www.nightprogrammer.org/wp-uploads/2013/02/multipage_tiff_example.tif) it works just fine, so my guess there is something peculiar with my TIFFs.

### Expected behavior

Having it saves as multi-layered tiff :)

### Debug logs

`-DBG- Internal VB error encountered in TIFF routine.  Err #10, This array is fixed or temporarily locked`

Debug: [DebugTiff.zip](https://github.com/tannerhelland/PhotoDemon/files/13688465/DebugTiff.zip)

**Comment by tannerhelland** [comment]
Hello @hi5 .  I am so sorry that you've encountered multiple image export bugs lately!

Fortunately for me, your bug reports are incredibly helpful, and the files you attached made it much easier for me to track down the problem.  Thank you.

This bug was entirely my fault.  Because TIFF files can be so large, PhotoDemon's TIFF exporter tries to find the smallest possible color-depth that works for each page.  One check it performs is for monochrome pages, and the check is simple enough - compare the first two unique colors found on each page, and if they are black and white, save that page as a monochrome one.

I just discovered that this simple function crashes on your TIFF files because it tries to compare the first two unique colors it finds on each page... but if the page is blank, there is only one unique color and it crashes when looking at the (non-existent) second unique color  🤦‍♂️ 

I am embarrassed and sorry for not thinking of this earlier.  I believe I have fixed the problem, and new nightly builds are already available.  Please let me know if further problems occur.

I hope to release a new stable 9.2 version soon with all the many bug-fixes since 9.0's release.  I just need to finish up a few minor feature enhancements that have taken longer than expected.

Thank you again for filing these bug reports so promptly.  I am excited to ship these important fixes to all users soon!

**Comment by hi5** [comment]
Excellent, glad the report was useful and apparently easy to fix. And don't worry about errors, nothing is without errors and there are simply too many edge cases to consider, and mutlipage TIFFs are quite exotic already, having poor or no support at all in other programs illustrates it as well.

I can confirm it works correctly now with build 230. 🍾

**Comment by tannerhelland** [comment]
Thank you so much for the follow-up!  1 problem down, 99 to go 😆
