### ISSUE TITLE
Cursor position reported on the status line is incorrect

### ISSUE THREAD

**Issue by daved163g** [tannerhelland/PhotoDemon#518]
### Version information
PhotoDemon_nightly 9.2 pre-alpha build 246

### Describe the bug
Test image is 1024 x 768 pixels.
The screen is a Dell U2413 with a PPI (pixels per inch) of 94 (16:10, 1920x1200).
Measurements given refer to the horizontal aspect: the vertical aspect has the same bug.
The error relates both to the overall size of the image (static value) and the instantaneous value of the cursor position as displayed on the status line.

There is absolutely no point in providing linear measurements if they are not reasonably accurate. I have checked several other photo apps and most are wrong, but not wildly so. For example, Corel’s ruler suggests it is using 100ppi.

Measurements (in column 4) are calculated from the inches value and confirmed (approximately) with a standard ruler.
    px     pixels              1024                   correct value
    in      inches             2600.96              10.89 inches
    cm    centimetres    6606.44              27.66 centimetres
    mm  millimetres      66064.38            2766 millimetres
    pt      points            187,269.1            784.08 points    (1pt is marginally less than 1/72”)
    pc     picas              15,605.8              9408.96 picas    (1pc is 12 points)
    pc     percentage    100                     (percentage might make more sense than picas!)

I have no idea how the erroneous values were arrived at: all values other than pixels are clearly way out of the ballpark.

### How can I reproduce the bug?
Just run PhotoDemon, load an image of known size and observe the status line.

### Expected behavior
 In providing metrics for the image size the following is needed (again, we’ll work with just the horizontal):

    Determine the screen width in pixels    
    Determine the pixels per inch, or the pixels per centimetre 
         I don’t know if it’s possible to obtain this from the OS
             https://stackoverflow.com/questions/12652835/getting-actual-screen-dpi-ppi-under-windows
         the user may need to provide this and guidance might be needed.
    Calculate the precise width of a pixel.
    Calculate everything else based on the actual pixel size.

There may be better methods – it depends on what information is exposed to the operating system.

### Debug logs

If you are using a nightly build, or if PhotoDemon has crashed more than once, it will automatically generate Debug Logs inside the program's `Data/Debug` folder.  If you can zip up all files in that folder and attach them to this bug report, that is a *huge* help.

### Sample images and/or screenshots

If applicable, please attach the image file(s) that caused the bug.  Screenshots or screen recordings of the problem can also help.  (PhotoDemon provides a built-in screen recording tool in the `Tools > Animated screen capture` menu.)

### Thank you!

As a "thank you" for your help, I am happy to add your name to PhotoDemon's contributor list.  Please let me know what name (and optional website link) you'd like me to use.

**Comment by tannerhelland** [comment]
Hello again @daved163g !  Thank you for filing this issue.

The reason you see varying results with real-world measurements like "inch" or "cm" is because those measurements reflect *print measurements*, not *on-screen measurements*.  The exact calculation is made using the image's embedded DPI value, which can also be set via the `Image > Resize menu`:

![image](https://github.com/tannerhelland/PhotoDemon/assets/1930029/78243a64-d9a1-4fc9-806f-38e2e2e49519)

These measurements are provided so that you can draw an e.g. 1-inch box that will be one inch *when the document is printed onto paper*.

If you use the `Image > Resize` tool to set a photo PPI value identical to your screen PPI, you'd think the on-screen measurements would be 1:1 accurate... but sadly, that is not always the case.  System settings like `System > Display > Scale` (on Windows 11, similar settings exist on older versions) will auto-scale apps by a proportionate size, producing a different "effective" DPI value than the display's native resolution.  Multi-monitor settings are even more complex since each display might have a different native DPI and scaled DPI, each with its own complications.

For this reason, in a photo editor, real-world measurements like "inch" and "cm" always operate on *print dimensions*.  

Hope that helps!

**Comment by tannerhelland** [comment]
Just a quick follow-up - that image resolution value in the `Image > Resize` screen traditionally comes from the image file itself.  (Most formats provide an optional field for print resolution.)

If no value is provided by the image file itself, a default resolution value is assumed.  The default value used can vary by image format for any number of historical reasons.  This typically explains differences between photo editors - they may assume different default resolution values when none are provided.

You can freely change an image's resolution at any time via `Image > Resize` without changing actual image dimensions (in pixels).  Different editors should display identical on-screen rulers for identical zoom values for any images with identical print sizes and resolutions (e.g. "8x10 inches at 300 DPI").

This is what allows you to import e.g. an arbitrary iPhone photo, then prep it for printing at 8x10 size at a fixed quality of 300 DPI (with the photo editor auto-calculating what those values needs to be in pixels).  If you set an image to that size, for example, the on-screen rulers will reflect the *print size* of 4x6, ignoring screen resolution.  If you zoom in to 200% or out to 50%, the rulers will always maintain the same 8x10 scale against the image's boundaries.

Screenshots to demonstrate:

### Setting image print size on a digital photo (note the inch measurements of 8"x10" at 300 DPI):
![image](https://github.com/tannerhelland/PhotoDemon/assets/1930029/d72879b4-7da0-4203-8818-30d3f839b8ad)

### Note the 8x10 measurements in "inches" in the on-screen rulers:
![image](https://github.com/tannerhelland/PhotoDemon/assets/1930029/055c81f7-fa52-4edd-b64e-879bbe5d3986)

### ...and again, note the same 8x10 measurements at a different zoom value (they still map directly to image boundaries):
![image](https://github.com/tannerhelland/PhotoDemon/assets/1930029/661e145b-6821-42f3-bbf8-bea72b74060f)
