### ISSUE TITLE
PD don't show the untranslated phrases ?

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#540]
###
Hello , 
As you added options to export images and layers, I saw that some phrases were not translated in french interface:
PD shows nothing as "untranslated phrases" so, with the software "sublime text" I edited the xml langage file and find some untranslated phrases.      PD shows also only 12 "translated phrases" . ( 12? it seems to show a bit more ) , before I could acess all the phrases (I didn't look at the french translation as often as before, ).

I send you a french file ( made with the sublime text software) with updated translation ("image to file", "layers to file" etc) - 
### Merci ! ( for your software and all the care to your users requests ! Have a nice day !
![PD langage editor French  1](https://github.com/tannerhelland/PhotoDemon/assets/62914748/332b9e14-de36-4f3c-8aa9-9324cf514d99)
![PD langage editor french 2](https://github.com/tannerhelland/PhotoDemon/assets/62914748/6fc0af0c-4612-44f7-9317-f57fc792f578)
[French.zip](https://github.com/tannerhelland/PhotoDemon/files/14473167/French.zip)

**Comment by tannerhelland** [comment]
Thank you for the updated French localization and bug report, @mizka76 !  I am very grateful for your ongoing help.  Nightly builds have been updated with your latest French language file.

Unfortunately, I cannot seem to reproduce the translation tool problem locally!  I have tried on several PCs but the language tool appears to find the right number of phrases:

![image](https://github.com/tannerhelland/PhotoDemon/assets/1930029/53179b09-edc4-41b8-8efb-dbd1d28d0036)

Is it possible that another program was used to edit the language file at some point?  I ask because if the language file was not saved in the same encoding that PhotoDemon natively uses, it might confuse the language editor...  (I am struggling to think of another explanation for the strange behavior!)

Either way, I will keep playing with the Language Editor periodically to see if I can trigger the same bug.  Thank you again for letting me know about this issue.

**Comment by tannerhelland** [comment]
Thank you, @mizka76 !  I appreciate you trying a fresh nightly build.  

It should always be okay to edit PhotoDemon language files with other text editors, as long as the editor saves the file in the same format (UTF-8).  If you encounter any trouble again, please let me know and I will investigate again.

Thank you also for the updated French language file.  I will merge it in the next few minutes!
